### ISSUE TITLE
move varnish invalidation to cartodb-postgres

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb-postgresql#10]
Since ideally the platform should work without rails app (cartodbpostgres + sql api + maps api) the invalidation should be in the extension so:
- CDB_Invalidate_Varnish() method should be in cartodb-postgres
- there should be some CDB_Config_Varnish or similar to configure it (it will be called from rails app or manually if you are not using it)
- If it's not configured, varnish invalidation is not used

As a side not maybe we should remove varnish name from the function and start to use something more generic, like CacheService. We know that the interface will be the same if we move to a different invalidation service.

**Comment by zenitraM** [comment]
Necro-bumping this, now that we need to do some tweaks on the trigger (see https://github.com/CartoDB/cartodb/issues/6773) would this be a good opportunity to do this change?

**Comment by Algunenano** [comment]
Stale
