### ISSUE TITLE
function cdb_columnnames(name) does not exist

### ISSUE THREAD

**Issue by elesdoar** [CartoDB/cartodb-postgresql#102]
Query:

```sql
WITH t1 AS (SELECT CDB_UserTables() table_name) 
SELECT CDB_ColumnNames(t1.table_name) column_name
FROM t1
```
Return function cdb_columnnames(name) does not exist

**Comment by javisantana** [comment]
Could you provide more info, it work as expected for me:

https://rambo-test.cartodb.com/api/v1/sql?q=select%20CDB_ColumnNames(%27testing%27)

**Comment by elesdoar** [comment]
Simple query:

```sql
SELECT CDB_ColumnNames('some tablename') column_name
```
It works correctly, but nested query

```sql
WITH t1 AS (SELECT CDB_UserTables() table_name) 
SELECT CDB_ColumnNames(t1.table_name) column_name
FROM t1
```
It not works, return `function cdb_columnnames(name) does not exist` :tired_face:

**Comment by rochoa** [comment]
@elesdoar, as `CDB_ColumnNames` expects a regclass and `CDB_UserTables` returns set of `name` casting to `::text` or `::regclass` should do the trick. Try with:

```sql
WITH t1 AS (SELECT CDB_UserTables()::regclass table_name)
SELECT t1.table_name,
CDB_ColumnNames(t1.table_name) column_name
FROM t1
```

**Comment by elesdoar** [comment]
:scream: :scream: Thank you, It's perfect for me.
