### ISSUE TITLE
CDB_CONF configuration table

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb-postgresql#115]
- `cartodb.CDB_CONF` table.
- `cartodb.CDB_Conf_SetConf`.
- `cartodb.CDB_Conf_RemoveConf`
- `cartodb.CDB_Conf_GetConf`

Cached with SD.

Will be merged with CartoDB/cartodb-postgresql#104

Alternatives for `CDB_Conf.conf` type:
A) Different entry for each value.
B) Force JSON type for value.
C) Keep text type for value and let clients store whatever they need.
*X) other*

**Comment by juanignaciosl** [comment]
1.- @rochoa , @javisantana has declined the decision of value storage format. Which one would you prefer?

2.- I've done some changes in order to secure access to configuration. See 70fe432102539991a750eee5b9dc71a9628a232f. Since CDB_Conf has sensitive information we don't want anybody to have access. I've dropped read permission on that table so only a superuser can read it. This forces the need of add `SECURITY DEFINER` to functions needing configuration read. In this case, to `_CDB_Group_API_Auth` ([PR](https://github.com/CartoDB/cartodb-postgresql/pull/104/files)). Are you ok with this, or am I missing something? cc @javisantana

**Comment by rochoa** [comment]
I proposed some alternatives:

1. key+value per row: limited to text, have to handle results

```sql
DROP TABLE cartodb.CDB_CONF;
CREATE TABLE IF NOT EXISTS cartodb.CDB_CONF ( CONF_NAME TEXT, CONF_KEY TEXT, CONF_VALUE TEXT NOT NULL, PRIMARY KEY (CONF_NAME, CONF_KEY));

DELETE FROM cartodb.CDB_CONF;
INSERT INTO cartodb.CDB_CONF (CONF_NAME, CONF_KEY, CONF_VALUE) VALUES ('groups_api', 'host', 'localhost'),('groups_api', 'port', '5432');
SELECT conf_key, conf_value FROM cartodb.CDB_CONF WHERE conf_name = 'groups_api';
```

2. json config value: easy to cast values, can add some kind of validation to check all keys are present, postgresql will validate json is valid for you

```sql
DROP TABLE cartodb.CDB_CONF;
CREATE TABLE IF NOT EXISTS cartodb.CDB_CONF ( CONF_KEY TEXT PRIMARY KEY, CONF_VALUE JSON NOT NULL);

DELETE FROM cartodb.CDB_CONF;
INSERT INTO cartodb.CDB_CONF (CONF_KEY, CONF_VALUE) VALUES ('groups_api', '{"host": "localhost", "port": 5432}');
SELECT CONF_VALUE->>'host' host, cast(CONF_VALUE->>'port' as int4) port
  FROM cartodb.CDB_CONF
  WHERE CONF_KEY = 'groups_api';
    -- AND ARRAY(SELECT json_object_keys(CONF_VALUE) FROM cartodb.CDB_CONF WHERE CONF_KEY = 'groups_api') @> ARRAY['host', 'port'] -- adds validation
```

3. use hstore extension: requires installing the extension (it comes by default with postgresql), validations are also possible, easy to cast values, powerful operators and functions

```sql
DROP TABLE cartodb.CDB_CONF;
CREATE TABLE IF NOT EXISTS cartodb.CDB_CONF ( CONF_KEY TEXT PRIMARY KEY, CONF_VALUE HSTORE NOT NULL);
INSERT INTO cartodb.CDB_CONF (CONF_KEY, CONF_VALUE) VALUES ('groups_api', 'host=>"localhost", port=> 5432');

SELECT conf_value -> 'host', cast(conf_value -> 'port' as int4) FROM cartodb.CDB_CONF
  WHERE CONF_KEY = 'groups_api';
    -- AND conf_value ?& ARRAY['host','port']; -- adds validation

SELECT conf_value -> ARRAY['host','port'] FROM cartodb.CDB_CONF
  WHERE CONF_KEY = 'groups_api';
    -- AND conf_value ?& ARRAY['host','port']; -- adds validation

SELECT %# conf_value FROM cartodb.CDB_CONF
  WHERE CONF_KEY = 'groups_api';
    -- AND conf_value ?& ARRAY['host','port']; -- adds validation
```

I personally would go with option 2 because json is easier to understand if you haven't been exposed to hstore before, provide more or less the same functionality than hstore and we don't need to install hstore extension.

**Comment by juanignaciosl** [comment]
Done 2. Closing this, won't merge PR yet. Thank everybody :-)

**Comment by rochoa** [comment]
Perfect! :rocket:
