### ISSUE TITLE
import error cartodb-staging

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb-postgresql#116]
I've export the world_borders dataset from my account at user.cartodb.com in two formats (.csv and .geoJson) and I've tried to upload them in my account in user.cartodb-staging.com, but the import process fail.

In the logs it shows this error:

Exception: PG::Error: ERROR:  CDB(_CDB_Rewrite_Table:XX000:transform: couldn't project point (180 -90 0): tolerance condition error (-20)): CREATE TABLE public.world_borders_1_b456b0650d11b0560adb1295e717646d AS SELECT cartodb_id,ST_Transform(the_geom,4326)

**Comment by rafatower** [comment]
cc/ @pramsey this might be a blocker. I'll take a further look and try to provide more debugging info. Any help appreciated.

**Comment by pramsey** [comment]
Presumably this isn't a new problem? How do we create `the_geom_webmercator` right now that avoids the problem of infinities at the edges of mercator?
```
postgis22=# select st_transform('SRID=4326;POINT(180 -90)'::geometry,3857);
ERROR:  transform: couldn't project point (180 -90 0): tolerance condition error (-20)
```

**Comment by javisantana** [comment]
we do some nasty things to avoid that problem: https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_TransformToWebmercator.sql#L8

**Comment by pramsey** [comment]
OK, so this is a relatively easy fix then.

**Comment by javisantana** [comment]
@pramsey do you think that could be improved?

**Comment by rafatower** [comment]
I'd just use that function directly and we can defer improvements to the next version. Opinions?

**Comment by pramsey** [comment]
Mercator function looks fine to me, use that.

**Comment by javisantana** [comment]
<censored>
