### ISSUE TITLE
Import dataset fail in staging

### ISSUE THREAD

**Issue by MariaCheca** [CartoDB/cartodb-postgresql#117]
Importing a dataset in staging gives an upload error that doesn't happen in production.

Follow these steps to reproduce it:

1. Download [this dataset](https://mariacheca.cartodb.com/tables/public.meteorite_landings/public/map) as csv.
2. Try to upload it from the dataset uploader with version 0.9.1 of the extension **disabling data type guessing**.
3. Fails, returning this:
```
2015-08-20 09:11:03 UTC: Exception: PG::Error: ERROR:  column "the_geom" of relation "public_1" does not exist
CONTEXT:  SQL statement "CREATE trigger update_the_geom_webmercator_trigger BEFORE INSERT OR UPDATE OF the_geom ON public_1 FOR EACH ROW EXECUTE PROCEDURE cartodb._CDB_upd

app/models/table.rb:1176:in `block in cartodbfy'
```

**Comment by rafatower** [comment]
I tested it without [this patch](https://github.com/CartoDB/cartodb-postgresql/commit/5dd497bf202b8fd23f31aa20b19c3f9f738dcdb3) (against 0.9.0) and it worked ok. I'll keep investigating...

**Comment by rafatower** [comment]
Couldn't reproduce it against 0.9.1 either in local.

**Comment by rafatower** [comment]
The disabling type guessing is fundamental to reproduce the issue. The trace
```
2015-08-20 10:08:44 UTC ERROR:  column "the_geom" of relation "public_2" does not exist
2015-08-20 10:08:44 UTC CONTEXT:  SQL statement "CREATE trigger update_the_geom_webmercator_trigger BEFORE INSERT OR UPDATE OF the_geom ON public_2 FOR EACH ROW EXECUTE PROCEDURE cartodb._CDB_update_the_geom_webmercator()"
        PL/pgSQL function _cdb_create_triggers(text,regclass) line 16 at EXECUTE statement
        SQL statement "SELECT _CDB_create_triggers(destschema, destoid)"
        PL/pgSQL function cdb_cartodbfytable(text,regclass) line 60 at PERFORM
2015-08-20 10:08:44 UTC STATEMENT:  
                SELECT cartodb.CDB_CartodbfyTable('public'::TEXT,'public.public_2'::REGCLASS);
```

I'll try to provide a simpler scenario to reproduce. I think what happens is that without type guessing `the_geom` is imported as string and discarded as valid geom column.

**Comment by rafatower** [comment]
Right before cdb_cartodbfytable:
```
\d public                                                                                                                                                                           
       Table "public.public"
   Column    |   Type   | Modifiers 
-------------+----------+-----------
 name        | text     | 
 nametype    | text     | 
 recclass    | text     | 
 mass_g      | text     | 
 fall        | text     | 
 year        | text     | 
 id          | text     | 
 reclat      | text     | 
 reclong     | text     | 
 geolocation | text     | 
 the_geom    | geometry | 
 cartodb_id  | text     | 
 created_at  | text     | 
 updated_at  | text     | 
```
so it is supposed to have a column `the_geom`

**Comment by rafatower** [comment]
Full trace [here](https://gist.github.com/rafatower/be95c40639d9195e949e)

Some relevant things:
```
DEBUG:  CDB(_CDB_Rewrite_Table): has_usable_geoms f
    222:DEBUG:  CDB(_CDB_Rewrite_Table): CREATE TABLE public.public_86667d092de1284a1a3fe1230883143f AS SELECT nextval('public.public_cartodb_id_seq') AS cartodb_id FROM public
    225:DEBUG:  CDB(_CDB_Rewrite_Table): CREATE TABLE public.public_86667d092de1284a1a3fe1230883143f AS SELECT nextval('public.public_cartodb_id_seq') AS cartodb_id FROM public
    230:DEBUG:  CDB(_CDB_Rewrite_Table): ALTER TABLE public.public_86667d092de1284a1a3fe1230883143f ALTER COLUMN cartodb_id SET DEFAULT nextval('public.public_cartodb_id_seq')
    235:DEBUG:  CDB(_CDB_Rewrite_Table): ALTER SEQUENCE public.public_cartodb_id_seq OWNED BY public.public_86667d092de1284a1a3fe1230883143f.cartodb_id
    280:DEBUG:  CDB(_CDB_Rewrite_Table): ALTER TABLE public.public_86667d092de1284a1a3fe1230883143f RENAME TO public
```

**Comment by rafatower** [comment]
`DEBUG:  CDB(_CDB_Rewrite_Table): found no extra columns` ???

**Comment by rafatower** [comment]
@javisantana @pramsey this is getting funnier. There are lots of corner cases hidden in IF/ELSE branches. I'll do my best to get a fix with minimal impact for this.

**Comment by pramsey** [comment]
Well, I can understand having the text `the_geom` case fail, *although* since you patched the function to create NULL'ed columns in the case of missing a geometry column, even that case shouldn't fail, it should just do a bad import. The "has_usable_geoms f" log entry just means that the function couldn't find geometry columns it could use *without rewriting the table* so a table rewrite would be required. Basically the "usable geoms" function just checks if there are pre-existing geometry columns in 4326 and 3857, and if there are, renames them to the right thing, no table re-write required.

**Comment by rafatower** [comment]
I understand the high level approach and I'm ok with it. What I'm saying is that we can have many scenarios and we're having problems with some of them. Just trying to find the most pragmatic solution.

> if there are pre-existing geometry columns in 4326 and 3857
we can have many combinations there: 4326 and 3857 present, one present and the other absent, both absent.

https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_CartodbfyTable.sql#L901-L936

I suspect of the code around those lines. `geom_column_source` should be set to `''` in the NOT FOUND case, right?

**Comment by pramsey** [comment]
Well, the question is what conditions are getting it into the NOT FOUND case in the first place... because it's clearly not expected. It looks like a geometry-typed column with a zero-valued SRID slips into the gaps between the conditions.

`geom_column_source` is initialized to `''` up top, so that's taken care of. And we have the following conditions

* can't find a column with type `geometry` -- add two NULL::geometry columns
* find a column with type geometry
  * has an SRID? transform it to 4326 and 3857 
  * has no SRID? mmmmmm...

**Comment by rafatower** [comment]
```
# select Find_SRID('public', 'public', 'the_geom');
 find_srid 
-----------
         0
(1 row)
```
confirmed. BTW, why don't we use Find_SRID?

**Comment by pramsey** [comment]
`find_srid()` depends on looking at geometry_columns, which only has valid info for columns that are declared with an SRID, ie `geometry(point, 4326)`. Unfortunately we should probably be looking at an amalgam of checking the geometry_columns table, and then if that's zero checking the first geometry. find_srid would handle the case of the empty table, unlike the current code

**Comment by pramsey** [comment]
```
postgis22=# create table foo ( g geometry );
CREATE TABLE
postgis22=# insert into foo values ('SRID=2;POINT(1 1)');
INSERT 0 1
postgis22=# select * from geometry_columns ;
 f_table_catalog | f_table_schema | f_table_name | f_geometry_column | coord_dimension | srid |   type   
-----------------+----------------+--------------+-------------------+-----------------+------+----------
 postgis22       | public         | foo          | g                 |               2 |    0 | GEOMETRY
(1 row)

postgis22=# select st_srid(g) from foo ;
 st_srid 
---------
       2
(1 row)
```

**Comment by rafatower** [comment]
The problem is a combination of two unfortunate things:
1. From [rails code](https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/georeferencer.rb#L91): `2015-08-20 09:10:59 UTC: Creating the_geom from the_geom column` but without SRID

2. From the extension, hitting the case pointed  out above.

I'd make the extension resilient to that problem and also fix rails code.

**Comment by rafatower** [comment]
https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/column.rb#L165-L179

**Comment by pramsey** [comment]
Thou shalt have no 3d geometry? Not as a core matter of philosophy, since we can create them and map them by hand via SQL API. But importer forces that... we could avoid doing in in SQL if we want to keep the importer behavior by using the `-dim 2` flag on ogr2ogr?

**Comment by rafatower** [comment]
Apparently the old behavior was to force the SRID for the_geom and the_geom_webmercator columns: https://github.com/CartoDB/cartodb-postgresql/blob/513488da0ef0cc5516a774f2a8dc7022675ad303/scripts-available/CDB_CartodbfyTable.sql#L335-L339

**Comment by pramsey** [comment]
We force our outputs to have the right SRIDs in the column defs too, but that doesn't help us if the inputs are undefined, right?

**Comment by rafatower** [comment]
Right. OTOH it was a convenient assumption that if there was a the_geom then it had 4326. Breaking with that assumption has consequences, especially in the export/import scenario.

**Comment by rafatower** [comment]
@pramsey do you think you can write a function to force srid of the geom to 4326 if it is not set? would it make you feel bad? after considering several options I don't see a better one to go live.

**Comment by rafatower** [comment]
my proposal:
```patch
diff --git a/scripts-available/CDB_CartodbfyTable.sql b/scripts-available/CDB_CartodbfyTable.sql
index 46bd362..22f660f 100644
--- a/scripts-available/CDB_CartodbfyTable.sql
+++ b/scripts-available/CDB_CartodbfyTable.sql
@@ -925,12 +925,15 @@ BEGIN
       AND t.typname = 'geometry'
       AND a.attnum > 0
       AND NOT a.attisdropped
-      AND (postgis_typmod_srid(a.atttypmod) > 0 OR srid.srid > 0)
+      AND ((postgis_typmod_srid(a.atttypmod) > 0 OR srid.srid > 0) OR (a.attname = const.geomcol))
       ORDER BY a.attnum
       LIMIT 1;
     
       IF FOUND THEN
         sql := sql || geom_transform_sql;
+      ELSE
+        RAISE NOTICE 'rtorre: spetial tricky one';
+       geom_column_source := '';
       END IF;
 
     END IF;
```

**Comment by pramsey** [comment]
I think just go w/ good old SQL

CASE WHEN st_srid(geom) = 0 THEN st_setsrid(geom,4326) ELSE geom END

**Comment by rafatower** [comment]
After giving it some thought I think you're right. Paul, could you please write the code to force cartodb columns to the right type if they are present?

**Comment by rafatower** [comment]
Reviewing tests, I think this was a mistake from my side: 010dd13

Another interesting changeset that should've covered right this case: bb68579
