### ISSUE TITLE
Cannot upgrade extension if dependency on CDB_UserTables

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb-postgresql#120]
At the time, in order to migrate with a signature change in CDB_UserTables a DROP FUNCTION IF EXISTS was added. The problem is that it prevents upgrades if there are objects in DB dependent on it. Remove the DROP.

**Comment by rafatower** [comment]
The morale of this is again: do not change public function signatures. Better creating new ones and mark old ones as deprecated before removing

**Comment by javisantana** [comment]
In which case there is a dependency on CDB_UserTables?

**Comment by rafatower** [comment]
When the user defines a view in terms of cdb_usertables for instance.

**Comment by rafatower** [comment]
This is the line to remove: https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_UserTables.sql#L8

which by the way was added by me here: https://github.com/CartoDB/cartodb-postgresql/commit/a6fd829669aa8c3c42afd0750e8b52b95d716dc8

(creating this issue might seem a bit overkilling just to remove a line but I like to document the reason of the changes)

**Comment by rafatower** [comment]
Reviewing tests, I think this was a mistake from my side: https://github.com/CartoDB/cartodb-postgresql/commit/010dd13e4dd6f526b409473b47828107f6fc35b5
