### ISSUE TITLE
CDB_ColumnNames should honor regclass

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb-postgresql#122]
[CDB_ColumnNames current implementation](https://github.com/CartoDB/cartodb-postgresql/blob/0.9.1/scripts-available/CDB_ColumnNames.sql) returns columns for any table matching the name.

When having multiple tables with same name but in a different schema it will report the column name from all the tables.

`regclass` should be considered when providing qualified table names.

**Comment by iriberri** [comment]
SB/6362235

**Comment by javisantana** [comment]
why not using the oid so we don't need to add a filter by schema?

@iriberri CDB_ColumnNames is not public api, ping the user about this.

**Comment by rochoa** [comment]
You are right, actually the signature is `CDB_ColumnNames(REGCLASS)` so it should be a bugfix more than a new feature as it's already possible to do:

```sql
select CDB_ColumnNames('foo.table_name');
select CDB_ColumnNames('bar.table_name');
```
