### ISSUE TITLE
CDB_QuotaTest fail

### ISSUE THREAD

**Issue by khuevu** [CartoDB/cartodb-postgresql#125]
Hi, 
When I am running install check, my CDB_Quota test fails. It always fails on my fresh installation (Ubuntu 12.04 32 bit). I follow the cartoDB installation guide. 

The difference between result and expected is: 

result: ERROR:  Quota exceeded by 487.998046875KB
expected: ERROR:  Quota exceeded by 567.998046875KB

**Comment by khuevu** [comment]
I guess it is the problem with precision when using 32 bit. The test passes in my 64 bit installation.

**Comment by Algunenano** [comment]
Should be ok now
