### ISSUE TITLE
failed tests on [test_organization]

### ISSUE THREAD

**Issue by drzhouq** [CartoDB/cartodb-postgresql#132]
Followed the exact instructions to install postgres, pg_schema_triggers and carted-postgresq. It failed tests on [test_orgainzation] Error 1
The following tests are failing:
    test_cdb_querytables_returns_schema_and_table_name
    test_cdb_querytables_returns_schema_and_table_name_for_several_schemas
    test_cdb_querytables_does_not_return_functions_as_part_of_the_resultset

postgresql 9.3/ubuntu 12.04/latest schema triggers.

**Comment by Algunenano** [comment]
Should be ok now
