### ISSUE TITLE
ERROR:  CDB(_CDB_Has_Usable_Geom:42701:column "the_geom" of relation "completter" already exists)

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb-postgresql#141]
When importing a file that contains an attribute called "wkt" which contains the geometry written in WKT for every feature, this error is raised.

````
2015-09-08 14:35:22 UTC: Before persisting metadata 'completter' data_import_id: f5b1026b-3d72-491e-b1d0-569fc70815fe
2015-09-08 14:35:26 UTC: Exception: PG::Error: ERROR:  CDB(_CDB_Has_Usable_Geom:42701:column "the_geom" of relation "completter" already exists): ALTER TABLE completter RENAME COLUMN wkb_geometry TO the_geom
CONTEXT:  SQL statement "SELECT _CDB_SQL(sql,'_CDB_Has_Usable_Geom')"
PL/
2015-09-08 14:35:26 UTC: ["/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `async_exec'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'", "/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/1.9.1/gems/sequel-3.42.0/lib/sequel/database/logging.rb:33:in `log_yield'",
````

Renaming the "wkt" column to other thing, like "myk", makes the upload work and the system generates the_geom column appropriately.

**To reproduce**:

* Failing file: https://gist.githubusercontent.com/iriberri/74153be4d9628915003e/raw/46c7d1845b4926a296f3d3422a64c0342ddcbd8f/completter_fail.kml
* Working file: https://gist.githubusercontent.com/iriberri/84c101b2c0beb1377168/raw/070416056da1eb43ef32cfa2973486801b95d03d/completter_work.kml

**Comment by iriberri** [comment]
Another one, pasting here the error to be able to recognise the failing file later:

CDB(_CDB_Has_Usable_Geom:42701:column \"the_geom\" of relation \"maporgs9_9_15\" already exists): ALTER TABLE maporgs9_9_15 RENAME COLUMN wkb_geometry TO the_geom\nCONTEXT:

**Comment by rafatower** [comment]
At least in one of the cases the input table has both `the_geom` and `wkb_geometry`. Probably one of them to be thrown away.

**Comment by iriberri** [comment]
I just reproduced this error inside account by exporting and importing again the table "test2_copy" that lives in our current testing account. 

It contains some empty rows I added manually, so some the_geom are null, and the table also has lat/long columns (null too for these rows).

So yes, it seems there's a colision.

**Comment by rafatower** [comment]
Getting inconsistent results when trying to figure out the srid:
```sql
select _CDB_Geometry_SRID('many_geometry_columns'::regclass::oid, 'the_geom');
 _cdb_geometry_srid 
--------------------
                  0

SELECT ST_SRID(the_geom) AS srid FROM many_geometry_columns LIMIT 1;
 srid 
------
 4326
```

**Comment by iriberri** [comment]
...weird...

**Comment by rafatower** [comment]
The problem with the comment above is: the state of `FOUND` is not modified by `EXECUTE INTO`. Here's the documentation: 
http://www.postgresql.org/docs/9.4/static/plpgsql-statements.html#PLPGSQL-STATEMENTS-DIAGNOSTICS
and here some quick tests:
```sql
CREATE FUNCTION found_test()
RETURNS void
as $$
DECLARE
  rec RECORD;
BEGIN

  EXECUTE 'SELECT 1';

  IF FOUND THEN
    RAISE NOTICE 'EXECUTE modified FOUND';
  ELSE
    RAISE WARNING 'EXECUTE DID NOT modify FOUND!!!!';
  END IF;

  EXECUTE 'SELECT 1' INTO rec;

  IF FOUND THEN
    RAISE NOTICE 'EXECUTE INTO modified FOUND';
  ELSE
    RAISE WARNING 'EXECUTE INTO DID NOT modify FOUND!!!!';
  END IF;

END;
$$ LANGUAGE plpgsql;


SELECT found_test();
drop function found_test();
```
and here the result:
```
# psql -U postgres contrib_regression -f ~/found_test.sql 
CREATE FUNCTION
psql:/root/found_test.sql:28: WARNING:  EXECUTE DID NOT modify FOUND!!!!
psql:/root/found_test.sql:28: WARNING:  EXECUTE INTO DID NOT modify FOUND!!!!
```
Just FYI @pramsey: I'll review all usages of `EXECUTE` plus `FOUND` because they are widely used in cartodbfy code.

**Comment by pramsey** [comment]
Ug! Thanks @rafatower

**Comment by rafatower** [comment]
@pramsey I extracted the query on top of `_CDB_Has_Usable_Geom` to a function `_cdb_geom_candidate_columns` and run a small experiment:
```sql
DROP TABLE IF EXISTS many_geometry_columns;
CREATE TABLE many_geometry_columns (
       the_geom geometry,
       wkb_geometry geometry(MultiPoint,4326)
);
INSERT INTO many_geometry_columns (the_geom, wkb_geometry) VALUES
       ('0104000020E61000000100000001010000007108B023698052C03CEEA53A2E5D4440', '0104000020E61000000100000001010000007108B023698052C03CEEA53A2E5D4440'),
       ('0104000020E6100000010000000101000000864C9E57618052C0994F0C7F3C5B4440', '0104000020E6100000010000000101000000864C9E57618052C0994F0C7F3C5B4440');
SELECT * FROM _cdb_geom_candidate_columns('many_geometry_columns');
```
and this is what I got:
```
   attname    | srid | typname  |   desired_attname    | desired_srid 
--------------+------+----------+----------------------+--------------
 the_geom     |    0 | geometry | the_geom             |         4326
 the_geom     |    0 | geometry | the_geom_webmercator |         3857
 wkb_geometry | 4326 | geometry | the_geom             |         4326
 wkb_geometry | 4326 | geometry | the_geom_webmercator |         3857
```
(this is the Cartesian product `meta-info(att_name, srid) x desired(att_name, srid)`)

My question is how this can get along with this [line](https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_CartodbfyTable.sql#L739-L740):
```sql
    -- Name collision: right name (the_geom, the_geomwebmercator?)  but wrong type...
    IF r1.typname != 'geometry' AND r1.attname = r1.desired_attname THEN
```

I just want to make sure I'm not missing something important in the design of that function.

**Comment by pramsey** [comment]
Maybe, I'm not sure what your concern is... finding non-geometry types that have our preferred column names to either avoid clobbering them or converting them into geometries...

**Comment by rafatower** [comment]
My concern is understanding the algorithm, since it is setting flags and vars on a loop on the cartesian product of (attname,srid) x (desired_attname, desired_srid), and it also has side effects (renaming columns at the end) what are the guarantees it will deliver the intended results?

**Comment by ztephm** [comment]
ref S/B 6623933 (Private datasets are in ticket)

Expected: PostgreSQL INSERT INTO will put column info from user's _new dataset into original (blank) dataset that has same column names

Happening: 
![screen_shot_2015-09-14_at_6 01 37_pm](https://cloud.githubusercontent.com/assets/1779444/9880252/e8ac1aca-5b98-11e5-88c0-3002f7244081.png)

**Comment by rafatower** [comment]
@ztephm that's a different issue

**Comment by rafatower** [comment]
Fixed and released
