### ISSUE TITLE
CDB_StatsTest.sql test failing randomly

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb-postgresql#144]
Hey @ohasselblad 

The recently created test for CDB_Kurtosis and CDB_Skewness fails randomly, probably because random() distribution is not good enough with the number of elements we are using in that test.

Do you think we can use another synthetic input for the tests?

We could use tablefunc extension just for the test to use a normal distribution with [`normal_rand(int numvals, float8 mean, float8 stddev)`](http://www.postgresql.org/docs/9.3/static/tablefunc.html#AEN156601).

**Comment by ohasselblad** [comment]
I think we'd have the same problem with the normal distribution.

I can do an example with `generate_series(0,10000)::numeric / 10000` that should give the same value.

**Comment by rochoa** [comment]
What about playing with the values from the series:

```sql
WITH dist AS (
  SELECT CASE WHEN t > 5000 THEN t ELSE -t END AS val
  FROM generate_series(1,10000) t
)
```

**Comment by ohasselblad** [comment]
This produces consistent results:
http://eschbacher.cartodb.com/api/v2/sql?q=With%20a%20As%20(SELECT%20generate_series(0,10000)::numeric%20/%2010000.0%20i)%20SELECT%20abs(CDB_Kurtosis(array_agg(i))%20%2b%201.2)%20%3C%201e-3%20k,%20abs(CDB_Skewness(array_agg(i)))%20%3C%201e-3%20s%20FROM%20a

Based on:

```sql
With a As (SELECT generate_series(0,10000)::numeric / 10000.0 i)

SELECT 
  abs(CDB_Kurtosis(array_agg(i)) + 1.2) < 1e-3 k, 
  abs(CDB_Skewness(array_agg(i))) < 1e-3 s
FROM a
```

**Comment by rochoa** [comment]
Thanks for the help @ohasselblad !!

PR ready, will merge it once tests go green.

**Comment by ohasselblad** [comment]
Thanks for catching the error, @rochoa!
