### ISSUE TITLE
Make everything work again when restoring a pg_dump without needing to run Rails code to fix stuff afterwards

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb-postgresql#147]
See [docs](http://www.postgresql.org/docs/9.4/static/extend-extensions.html), section "Extension Configuration Tables".

**Comment by zenitraM** [comment]
Also, not only the table but also its grants

**Comment by rafatower** [comment]
Actually marked for backup here: https://github.com/CartoDB/cartodb-postgresql/blob/bce61c1e4359653134134097d269edae581e5660/scripts-available/CDB_ExtensionPost.sql

**Comment by rafatower** [comment]
@iriberri could you please add the workaround here once it's confirmed it works for the export/import case? thanks!

**Comment by iriberri** [comment]
As a workaround for this, we recommend you to run the `set_user_privileges_in_cartodb_schema` rake. This should populate the permissions in the `cdb_tablemetadata` table after you import the incomplete dump.


````
RAILS_ENV=development bundle exec rake cartodb:db:set_user_privileges_in_cartodb_schema[username]
```

We got confirmation that running this rake and a `db:migrate` solved the issue.
