### ISSUE TITLE
cartodbfy shall discard cartodb_id candidates that contain nulls

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb-postgresql#148]
Currently it checks for uniqueness but not for nullity.

**Comment by iriberri** [comment]
Just forced this behaviour by importing a file in which I nulled some cdb_ids in the testing environment, and yes, the error is there: 

 ERROR:  CDB(_CDB_Add_Indexes:23502:column \"cartodb_id\" contains null values): ALTER TABLE untitled_table_2_merge_1 ADD PRIMARY KEY (cartodb_id)\nCONTEXT:  SQL statement \"SELECT _CDB_SQL(sql, '_CDB_Add_Indexes')

(Probably this comment is useless for the record, but this way I make sure I report everything I'm facing...)

**Comment by rafatower** [comment]
Example csv file from iriberri:
```
cartodb_id,the_geom,untitled_table_1_name,untitled_table_1_city,name,column_1441980553921,city
1,0101000020E610000074D2FBC6D79E0DC05A643BDF4F354440,,Madrid,,,Madrid
2,0101000020E6100000739D465A2A6FE6BF28D53E1D8F214340,,Elche,,,Elche
,,,,,,
```

**Comment by iriberri** [comment]
https://cartodb.com/superadmin/users/11903/data_imports/09a4ba10-1572-4f47-99f2-a2744def0206

From today:
````
2015-10-02 13:03:32 UTC: Exception: PG::Error: ERROR:  CDB(_CDB_Add_Indexes:23502:column "cartodb_id" contains null values): ALTER TABLE download ADD PRIMARY KEY (cartodb_id)
CONTEXT:  SQL statement "SELECT _CDB_SQL(sql, '_CDB_Add_Indexes')"
PL/pgSQL function _cdb_add_indexes(regc
````

**Comment by rafatower** [comment]
fix is ready, to be deployed beginning of next week.
