### ISSUE TITLE
Dataset with null coordinates generates a point in (0,0) instead of a null geometry

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb-postgresql#150]
Sample test here: https://gist.githubusercontent.com/iriberri/d7725ceecd5d7065417b/raw/bee42c72140511c3eeb899b24de63ca6591dd2dc/example0.csv

![image](https://cloud.githubusercontent.com/assets/1730320/9815683/3d4b5f72-5898-11e5-96cc-0d6e45e9631a.png)

**Comment by rafatower** [comment]
does it happen in prod or in ded06-st?

**Comment by iriberri** [comment]
ded06-st

**Comment by gfiorav** [comment]
This is happening in production but not in my local instance.

**Comment by iriberri** [comment]
This is not cartodb-postgresql related, it's coming directly from ogr2ogr's output. Moving to https://github.com/CartoDB/cartodb/issues/7196
