### ISSUE TITLE
Test failing

### ISSUE THREAD

**Issue by Tom-Tom** [CartoDB/cartodb-postgresql#157]
In https://github.com/CartoDB/cartodb/issues/5421

> If I run installcheck after installing postgis, I get this error:
> `> Executing query 'SELECT count(*) FROM cdb_testmember_1.foo;' as cdb_testmember_2 ERROR: permission denied for schema cdb_testmember_1 LINE 1: SELECT count(*) FROM cdb_testmember_1.foo; ^ FAILED TO EXECUTE QUERY: SELECT count(*) FROM cdb_testmember_1.foo;`
> 
> And this fun one, which might be expected: `ERROR: relation "unexistent_example" does not exist LINE 1: SELECT CDB_TableMetadataTouch('unexistent_example'); ^ FAILED TO EXECUTE QUERY: SELECT CDB_TableMetadataTouch('unexistent_example');`
> 
> And at the end: The following tests are failing: `test_member_2_cannot_read_without_permission`

I have the same problem.

**Comment by odessky** [comment]
Confirmed. I have same error on Ubuntu 12.04 amd64.

**Comment by Algunenano** [comment]
Should be ok now
