### ISSUE TITLE
Sequence for cartodb_id incorrectly initialized when importing via gdal CartoDB driver

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb-postgresql#158]
Importing this way:
```
ogr2ogr2 \
>   --config CARTODB_API_URL https://rtorre2.cartodb.com/api/v2/sql \
>   --config CARTODB_API_KEY mysecretkey  \
>   -s_srs EPSG:4326 \
>   -t_srs EPSG:4326 \
>   -f CartoDB "CartoDB:rtorre" \
>   -oo X_POSSIBLE_NAMES=lon\* \
>   -oo Y_POSSIBLE_NAMES=lat\* \
>   -overwrite \
>   -dim 2 \
>   country_lat_long.csv
```
The [country_lat_long.csv](https://gist.githubusercontent.com/rafatower/17f5e9f8538006f1ea70/raw/35480000c85c66d890af3584fad6784484fd88ac/country_lat_long.csv) input file.

then when adding rows I got this error:
```
{"errors":["PG::Error: ERROR:  duplicate key value violates unique constraint \"country_lat_long_pkey\"\nDETAIL:  Key (cartodb_id)=(1) already exists.\n"]}
```

it seems like the created sequence is not set to max(cartodb_id) for some reason.

**Comment by rafatower** [comment]
Taking a closer look: the parameter `-f CartoDB:rtorre` did not match the URL nor the API_KEY (look at the bug desc) so there's something wrong, such as creating the table and/or sequence in the wrong schema.

I tested again with the correct combination and went fine.

**Comment by gfiorav** [comment]
What should be done with this ticket then?
