### ISSUE TITLE
An upgrade from 0.7.3 to 0.10.1 fails

### ISSUE THREAD

**Issue by azamorano** [CartoDB/cartodb-postgresql#160]
```
# ALTER EXTENSION cartodb UPDATE TO '0.10.1';
ERROR:  cannot change return type of existing function
HINT:  Use DROP FUNCTION cdb_usertables(text) first.
```

**Comment by rafatower** [comment]
Done.

For the record:
- I updated the branch 3.11.X in cartodb. See https://github.com/CartoDB/cartodb/commit/56a83be5478190413cca8abf672cd3b03c841953
- I updated the cdb tag to point to 0.10.2. See https://github.com/CartoDB/cartodb-postgresql/releases
