### ISSUE TITLE
Regression test fails

### ISSUE THREAD

**Issue by sindile** [CartoDB/cartodb-postgresql#166]
My environment is Ubuntu 12.04 with cartodb-postgresql master branch

I have seen the references to this error and have tried all of the suggestions but still I get the following errors.

============== running regression test queries        ==============
test test_setup               ... ok
test test_ddl_triggers        ... FAILED
test test/CDB_CartodbfyTableTest ... ok
test test/CDB_DigitSeparatorTest ... ok
test test/CDB_DistinctMeasureTest ... ok
test test/CDB_DistTypeTest    ... ok
test test/CDB_EqualIntervalBinsTest ... ok
test test/CDB_HeadsTailsBinsTest ... ok
test test/CDB_HexagonTest     ... ok
test test/CDB_JenksBinsTest   ... ok
test test/CDB_MathTest        ... ok
test test/CDB_QuantileBinsTest ... ok
test test/CDB_QueryStatementsTest ... ok
test test/CDB_QueryTablesTest ... FAILED
test test/CDB_QuotaTest       ... ok
test test/CDB_StatsTest       ... ok
test test/CDB_TransformToWebmercatorTest ... ok
test test/CDB_UserTablesTest  ... ok
test test/CDB_XYZ_ExtentTest  ... ok

Here is the output of regression.diff

**\* /home/sindile/Gitrepos/Cartodb/cartodb-postgresql/expected/test_ddl_trigger$
--- /home/sindile/Gitrepos/Cartodb/cartodb-postgresql/results/test_ddl_triggers$

---

**\* 157,163 ****
  FROM CDB_TableMetadata WHERE tabname = 'c.t3'::regclass;
   tabname | agecs
  ---------+-------
!  c.t3    |     0
  (1 row)

---

--- 157,163 ----
  FROM CDB_TableMetadata WHERE tabname = 'c.t3'::regclass;
   tabname | agecs
  ---------+-------
!  c.t3    |     1
  (1 row)

---

**Comment by Algunenano** [comment]
Should be ok now
