### ISSUE TITLE
Group test fail during CartoDB installation

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb-postgresql#179]
CartoDB installation process trigger group errors at test phase:

<img width="1440" alt="tests_summary" src="https://cloud.githubusercontent.com/assets/932968/11242397/b5bca3b4-8e01-11e5-8f00-2ca630864b47.png">

<img width="1440" alt="errors" src="https://cloud.githubusercontent.com/assets/932968/11242342/6268c6d4-8e01-11e5-8ddb-1fcfcd64c197.png">

cc @rafatower

**Comment by rafatower** [comment]
I lack a bit of context, but... could it be that those tests precisely
check that a given user does not have permissions to perform certain group
operations?

On Wed, Nov 18, 2015 at 2:34 PM, Juan Ignacio Sánchez Lara <
notifications@github.com> wrote:

> CartoDB installation process trigger group errors at test phase:
>
> [image: errors]
> <https://cloud.githubusercontent.com/assets/932968/11242342/6268c6d4-8e01-11e5-8ddb-1fcfcd64c197.png>
>
> cc @rafatower <https://github.com/rafatower>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb-postgresql/issues/179>.
>



-- 
*Rafa de la Torre*
DataServices Engineer www.cartodb.com

**Comment by juanignaciosl** [comment]
I haven't been able to check anything yet. The context is "CartoDB installation", when you get to the test step you get those errors.

**Comment by rafatower** [comment]
In the screenshot the ones reported as failed are the query tables tests, not the group ones. I meant for me is normal to have that kind of "expected errors" so I wouldn't look at the problem in the groups direction, just based on the screenshots.

**Comment by juanignaciosl** [comment]
There're two screenshots (maybe you are seeing the notification, I first attached only one screenshots). The general one is misleading but the second one is clear, it fails at group management functions. I don't know the test script structure, I don't understand why error is reported there.

**Comment by dsaenztagarro** [comment]
Hi guys, in order to give you as much information as possible I have attached the full log after running the command: sudo PGUSER=postgres make installcheck

The command is executed in a clean installation from ubuntu 12.04 LTS vagrant box.

Rafa, if you need any information from me, don't hesitate to contact me.

[installcheck.txt](https://github.com/CartoDB/cartodb-postgresql/files/37947/installcheck.txt)

**Comment by jgoizueta** [comment]
I think those `FAILED TO...` messages in the second screenshot are OK; queries are checked for failure. Test are passing as long as there's nothing like this at the end of the tests:

![image](https://cloud.githubusercontent.com/assets/5909/11344224/419eb450-9210-11e5-9e99-ae7e1e152a2f.png)

Note the:

```
The following tests are failing:
	test_member_2_cannot_read_without_permission
```

**Comment by dsaenztagarro** [comment]
Sorry guys, I would be worried about the error in the first screenshot:

**test test/CDB_QueryTablesTest .... FAILED**

I attached the second screenshot just because I thought it could help you...

As the second screenshot it's like a "false positive" (once again, sorry for the waste of time!) I attached the full log in the previous comment.

**Comment by rafatower** [comment]
Related to https://github.com/CartoDB/cartodb-postgresql/issues/142

Thanks for reporting!

**Comment by vaxhax** [comment]
<img width="571" alt="screenshot 2016-07-25 13 52 00" src="https://cloud.githubusercontent.com/assets/6936353/17113197/2abaeaae-526f-11e6-94a2-764777b4361b.png">

@jgoizueta not trying to necro the now aging thread, but I got the exact error you posted on 23 Nov 2015.  Is this related to #142 also?  Following the steps in the docs, using latest cartodb-postgresql tag as of today on fresh 12.0.4 x64 .

**Comment by Algunenano** [comment]
Should be ok now
