### ISSUE TITLE
When running CDB_CreateOverviews I get an error of missing function

### ISSUE THREAD

**Issue by jatorre** [CartoDB/cartodb-postgresql#206]
When running

SELECT CDB_CreateOverviews('table_2013_nyc_pothole_complaints_heat_map')

On my osm2 account I get an error saying:

"function min(boolean) does not exist"

![screen shot 2016-03-05 at 2 14 52 pm](https://cloud.githubusercontent.com/assets/127803/13549843/a8ea7028-e2dc-11e5-93e3-89385405e102.png)

**Comment by jgoizueta** [comment]
Version 0.14.4 of the cartodb extension fixed that (https://github.com/CartoDB/cartodb-postgresql/pull/214)

It has already been installed to all users so you should have it.

OTH we're about to release a new version of the extension that will produce better overviews (by adjusting some internal parameters for the aggregation grid size and zoom levels to generate).

**Comment by jatorre** [comment]
Managed to run it now.
