### ISSUE TITLE
Weird Makefile problem

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb-postgresql#213]
There's a problem with the doubled (escaped) backslahes here: https://github.com/CartoDB/cartodb-postgresql/blob/224b2ce39504f974cc47602fd49c3fecb60a5b27/Makefile#L126-L133

That was expected to generate single backslashes, but now in some systems it generates two backslahes. Actually the latter behaviour is most consistent, since it is the same result as executing the `echo` command directly in `bash`, not through `make`.

The only difference I've been able to find in the cases where the new behaviour (double slashes) occurs is that they're running bash 4.2.25 instead of 4.2.24. (Oddly enough, OSX with bash 3.2.25 behaves as 4.2.24 even though it includes the same patch as 4.2.25)

**Comment by jgoizueta** [comment]
Please @rafatower @ethervoid @iriberri can you report how are your local environments behave?

You can use this Makefile:

```
.PHONY: testing

testing:
	echo '\\set' > TEST1
	echo "\\set" > TEST2
````

Then post here the output of:

```
cat TEST1
cat TEST2
make --version
bash --version
```

**Comment by jgoizueta** [comment]
If we add `SHELL = bash` to the Makefile (so that `make` doesn't try to execute any command in its won) the double slash is preserved with any bash version. Really weird.

**Comment by iriberri** [comment]
In my dev env:

````
ubuntu@cdb:~/tmp/javitest$ make testing
echo '\\set' > TEST1
echo "\\set" > TEST2
echo '\set' > TEST3
ubuntu@cdb:~/tmp/javitest$ cat TEST1
\\set
ubuntu@cdb:~/tmp/javitest$ cat TEST2
\set
ubuntu@cdb:~/tmp/javitest$ cat TEST3
\set
ubuntu@cdb:~/tmp/javitest$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu
````

In OSX:

````
~/javitest $ make testing
echo '\\set' > TEST1
echo "\\set" > TEST2
echo '\set' > TEST3
cat TEST1                                                                                                                                   
cat TEST2
cat TEST3
make --version
~/javitest $ cat TEST1
\set
~/javitest $ cat TEST2
\set
~/javitest $ cat TEST3
\set
~/javitest $ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
````

**Comment by ethervoid** [comment]
OSX

10:51:16  /tmp 
$ cat TEST1
\set

 10:51:23  /tmp 
$ cat TEST2
\set

 10:51:26  /tmp 
$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

 10:51:28  /tmp 
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.

 10:51:30  /tmp 

VAGRANT

ubuntu@cdb-dev:/tmp$ make
echo '\\set' > TEST1
echo "\\set" > TEST2
ubuntu@cdb-dev:/tmp$ cat TEST1
\\set
ubuntu@cdb-dev:/tmp$ cat TEST2
\set
ubuntu@cdb-dev:/tmp$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu
ubuntu@cdb-dev:/tmp$ bash --version
GNU bash, version 4.2.25(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html
>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

On Mon, Mar 21, 2016 at 10:48 AM, Carla <notifications@github.com> wrote:

> In my dev env:
>
> ubuntu@cdb:~/tmp/javitest$ make testing
> echo '\\set' > TEST1
> echo "\\set" > TEST2
> echo '\set' > TEST3
> ubuntu@cdb:~/tmp/javitest$ cat TEST1
> \\set
> ubuntu@cdb:~/tmp/javitest$ cat TEST2
> \set
> ubuntu@cdb:~/tmp/javitest$ cat TEST3
> \set
> ubuntu@cdb:~/tmp/javitest$ make --version
> GNU Make 3.81
> Copyright (C) 2006  Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.
> There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
> PARTICULAR PURPOSE.
>
> This program built for x86_64-pc-linux-gnu
>
> In OSX:
>
> ~/javitest $ make testing
> echo '\\set' > TEST1
> echo "\\set" > TEST2
> echo '\set' > TEST3
> cat TEST1
> cat TEST2
> cat TEST3
> make --version
> ~/javitest $ cat TEST1
> \set
> ~/javitest $ cat TEST2
> \set
> ~/javitest $ cat TEST3
> \set
> ~/javitest $ make --version
> GNU Make 3.81
> Copyright (C) 2006  Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.
> There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
> PARTICULAR PURPOSE.
>
> This program built for i386-apple-darwin11.3.0
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb-postgresql/issues/213#issuecomment-199196645>
>



-- 
*Mario de Frutos Díeguez*
Software Developer

*CartoDB—Map Your World's Data*
Plaza de Callao 4, Planta 2 - Palacio de la Prensa
28013 Madrid, España
T: : +34.911.165.823
W: www.cartodb.com

Live sessions to learn CartoDB <http://cartodb.com/webinars/>
