### ISSUE TITLE
Add CDB_RenameOverviews()

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb-postgresql#216]
Add a function update overview table names when the base table is renamed.

TODO: should be called before renaming, the table, after, or be callable in both ways?

**Comment by iriberri** [comment]
If called after renaming, it's going to fail because CDB_Overviews will not return any overviews for the new regclass name.

**Comment by iriberri** [comment]
We can change CDB_Overviews first to accept a table name as a text so that this can be flexible.

**Comment by Algunenano** [comment]
Stale
