### ISSUE TITLE
Overload CDB_Overviews(), CDB_DropOverviews() to accept a (text) table name

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb-postgresql#217]
So that the caller of these functions can use them on tables that do not exist (e.g. having just been deleted).

CDB_DropOverviews(text) should delete remnant overview tables if they exist after having deleted the base table. 

CDB_Overviews(text) should return an empy list of overviews for tables that do not exist.

**Comment by Algunenano** [comment]
Never gonna happen
