### ISSUE TITLE
Overviews are really scattered

### ISSUE THREAD

**Issue by jatorre** [CartoDB/cartodb-postgresql#222]
When I create an overview, and the overviews are used, the overview are gridded too much.

This is what I see at different zoom levels. This is not a good representation of the data as it looks very gridded.

I guess it has to do that the overviews are done at 4x4 pixels?

I did not expect this, I thought we would be aggregating by 1x1 pixels to show actual density, if not it just looks like a grid map.

Is it possible to configure the "spatial" resolution of the aggregation?

![screen shot 2016-04-04 at 1 43 58 pm](https://cloud.githubusercontent.com/assets/127803/14257368/8d3d3c6a-fa6b-11e5-8803-bea8eda1d666.png)
![screen shot 2016-04-04 at 1 43 43 pm](https://cloud.githubusercontent.com/assets/127803/14257369/8d3eec90-fa6b-11e5-8810-52e3670b1ee3.png)
![screen shot 2016-04-04 at 1 43 31 pm](https://cloud.githubusercontent.com/assets/127803/14257371/8d436b58-fa6b-11e5-98be-4d31a3030579.png)
![screen shot 2016-04-04 at 1 43 24 pm](https://cloud.githubusercontent.com/assets/127803/14257370/8d41ca28-fa6b-11e5-9ea4-232a1854be0e.png)

**Comment by jatorre** [comment]
Actually for comparison between using overviews are not just by slightly changing the SQL

![screen shot 2016-04-04 at 1 51 58 pm](https://cloud.githubusercontent.com/assets/127803/14257585/761ce250-fa6c-11e5-9c3b-aea851ce1068.png)
![screen shot 2016-04-04 at 1 51 49 pm](https://cloud.githubusercontent.com/assets/127803/14257586/7622aaf0-fa6c-11e5-87a4-ef896c4da05c.png)

**Comment by jgoizueta** [comment]
Yes, we're working on that; there's a parameter controlling it and it was
fixed (in the cartodb extension) for our first overviews experiments. We're
about to release a new version where it has a more sensible default value
and is actually accesilble from the SQL API:
https://github.com/CartoDB/cartodb-postgresql/pull/221

You can get an idea of the effect of the parameter here:
https://github.com/CartoDB/cartodb-postgresql/issues/219#issuecomment-205239496

Good to know you're trying the overviews feature, I hope it is more
complete and smooth very soon, and please keep finding its limits so we can
make it better!

On Mon, Apr 4, 2016 at 7:52 PM, Javier de la Torre <notifications@github.com
> wrote:

> Actually for comparison between using overviews are not just by slightly
> changing the SQL
>
> [image: screen shot 2016-04-04 at 1 51 58 pm]
> <https://cloud.githubusercontent.com/assets/127803/14257585/761ce250-fa6c-11e5-9c3b-aea851ce1068.png>
> [image: screen shot 2016-04-04 at 1 51 49 pm]
> <https://cloud.githubusercontent.com/assets/127803/14257586/7622aaf0-fa6c-11e5-87a4-ef896c4da05c.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb-postgresql/issues/222#issuecomment-205414675>
>



-- 
*Javier Goizueta Napal*
Senior Developer

*CartoDB*
Plaza de Callao 4, 28013, Madrid, Spain
www.cartodb.com

**Comment by jgoizueta** [comment]
With the release 0.15.0 of the extension this has been solved
