### ISSUE TITLE
use mode when creating overviews for integer columns

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb-postgresql#245]
when a table has an integer column the avg is being calculated when you usually need the mode (they are categorical values)

**Comment by jgoizueta** [comment]
The problem is integer columns may represent categorical data or any other kind of magnitude (think population...)

**Comment by javisantana** [comment]
the final decision is:

- when the column has less than 20 different values -> mode for aggregation
- more than 20 -> avg
