### ISSUE TITLE
test/Makefile references out of tree file

### ISSUE THREAD

**Issue by pnorman** [CartoDB/cartodb-postgresql#248]
[test/Makefile](https://github.com/CartoDB/cartodb-postgresql/blob/master/test/Makefile) has a target which calls `bundle exec rspec ../../../spec/lib/sql_test_spec.rb`, which is outside cartodb-postgresql. Does this file exist elsewhere? Is this Makefile used?

**Comment by Algunenano** [comment]
No longer an issue
