### ISSUE TITLE
Overview levels greater than 23 can be created using bigints

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb-postgresql#260]
see #258

Performance impact should be tested. Code available in branch [bigint_overviews](https://github.com/CartoDB/cartodb-postgresql/tree/bigint_overviews)

**Comment by rafatower** [comment]
can this be closed?

**Comment by jgoizueta** [comment]
Still an open issue. We could discuss if it represents an improvement worth the effort (of measuring the performance impact and debugging it)

**Comment by jgoizueta** [comment]
After looking at the actual use of overviews and errors happening during its creation, this does not seem to be needed.
