### ISSUE TITLE
Should overviews tables size count for the user quota?

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb-postgresql#261]
Currently for raster table we count the base table size (fully) but not its overviews.
For regular tables (and its vector overviews) we count half of its size (to account for the overhead of having the webmercator geometry).

If we apply the same criterion to vector overviews as we do for raster overviews we should not count it's size... or we could decide to count a fraction of its size...

**Comment by jgoizueta** [comment]
cc @rafatower @javisantana

**Comment by jgoizueta** [comment]
https://github.com/CartoDB/cartodb-postgresql/blob/0.16.4/scripts-available/CDB_Quota.sql#L42-L48

Note that `is_overview` doesn't currently include vector overviews, only raster overviews

**Comment by rafatower** [comment]
I'd go for applying the existing raster criterion (simple and consistent).
