### ISSUE TITLE
Should limit the length of overview table names

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb-postgresql#271]
The name of CARTO tables is limited to a maximum of [63 characters](https://github.com/CartoDB/cartodb/blob/1a38b8707421fef1040ed1d6dde89a3a540bc770/lib/carto/db/sanitize.rb#L9),
according to PG's limit [NAMEDATALEN](https://www.postgresql.org/docs/9.5/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS)).

But when a overview table name is generated the name is extended and can overpass this limit.
This currently has the effect of having overview creation fail, since [here](https://github.com/CartoDB/cartodb-postgresql/blob/0.17.0/scripts-available/CDB_OverviewsSupport.sql#L129) the base table name will be truncated.

When generating overview table names we should limit them to `NAMEDATALEN`-1 characters (64) while at the same time taking care of avoiding duplicate names.

This affects also the handling of overviews in the import API [here](https://github.com/CartoDB/cartodb/blob/1a38b8707421fef1040ed1d6dde89a3a540bc770/app/services/carto/overviews_service.rb#L19)

**Comment by Algunenano** [comment]
Not happening
