### ISSUE TITLE
test test/CDB_QueryTablesTest ... FAILED

### ISSUE THREAD

**Issue by Baguewi** [CartoDB/cartodb-postgresql#278]
I am installing cartodb but I'm stuck on this error if someone can help me

============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test test_setup               ... ok
test test/CDB_CartodbfyTableTest ... ok
test test/CDB_DateToNumberTest ... ok
test test/CDB_DigitSeparatorTest ... ok
test test/CDB_DistinctMeasureTest ... ok
test test/CDB_DistTypeTest    ... ok
test test/CDB_EqualIntervalBinsTest ... ok
test test/CDB_GreatCircle     ... ok
test test/CDB_HeadsTailsBinsTest ... ok
test test/CDB_HelperTest      ... ok
test test/CDB_HexagonTest     ... ok
test test/CDB_JenksBinsTest   ... ok
test test/CDB_MathTest        ... ok
test test/CDB_OverviewsTest   ... ok
test test/CDB_QuantileBinsTest ... ok
test test/CDB_QueryStatementsTest ... ok
test test/CDB_QueryTablesTest ... FAILED
test test/CDB_QuotaTest       ... ok
test test/CDB_StatsTest       ... ok
test test/CDB_TransformToWebmercatorTest ... ok
test test/CDB_UserTablesTest  ... ok
test test/CDB_XYZ_ExtentTest  ... ok

=======================
 1 of 22 tests failed. 
=======================

The differences that caused some tests to fail can be viewed in the
file "/home/diallo/cartodb-postgresql/regression.diffs".  A copy of the test summary that you see
above is saved in the file "/home/diallo/cartodb-postgresql/regression.out".

make: *** [installcheck] Erreur 1

**Comment by jgoizueta** [comment]
@Baguewi can you post your `regression.diffs` contents after running the tests?

**Comment by Baguewi** [comment]
@jgoizueta here is my file regressio.diffs

*** /home/diallo/cartodb-postgresql/expected/test/CDB_QueryTablesTest.out	2016-10-10 15:04:29.545068000 +0200
--- /home/diallo/cartodb-postgresql/results/test/CDB_QueryTablesTest.out	2016-10-10 15:07:39.089068000 +0200
***************
*** 1,5 ****
  \set ECHO none
! SELECT * FROM geometry_columns|{pg_catalog.pg_attribute,pg_catalog.pg_class,pg_catalog.pg_constraint,pg_catalog.pg_namespace,pg_catalog.pg_type}
  SELECT a.attname FROM pg_class c JOIN pg_attribute a on (a.attrelid = c.oid)|{pg_catalog.pg_attribute,pg_catalog.pg_class}
  CREATE table "my'tab;le" as select 1|{}
  SELECT a.oid, b.oid FROM pg_class a, pg_class b|{pg_catalog.pg_class}
--- 1,5 ----
  \set ECHO none
! SELECT * FROM geometry_columns|{pg_catalog.pg_attribute,pg_catalog.pg_class,pg_catalog.pg_namespace,pg_catalog.pg_type}
  SELECT a.attname FROM pg_class c JOIN pg_attribute a on (a.attrelid = c.oid)|{pg_catalog.pg_attribute,pg_catalog.pg_class}
  CREATE table "my'tab;le" as select 1|{}
  SELECT a.oid, b.oid FROM pg_class a, pg_class b|{pg_catalog.pg_class}
***************
*** 21,24 ****
  DROP TABLE
  DROP SCHEMA
  SELECT
! * FROM geometry_columns|{pg_catalog.pg_attribute,pg_catalog.pg_class,pg_catalog.pg_constraint,pg_catalog.pg_namespace,pg_catalog.pg_type}
--- 21,24 ----
  DROP TABLE
  DROP SCHEMA
  SELECT
! * FROM geometry_columns|{pg_catalog.pg_attribute,pg_catalog.pg_class,pg_catalog.pg_namespace,pg_catalog.pg_type}

======================================================================

**Comment by jgoizueta** [comment]
What version of PostGIS are you using?

Seems like the tests expect version 2.2 and you have a different one (the `geometry_columns` view in your version doesn't use `pg_constraint`). This is not really relevant and you can ignore this test fail, but other parts of CARTO will expect PostGIS >= 2.2, so  you should make check it.

**Comment by Baguewi** [comment]
I use version 2.2.3 of PostGIS.

My tests pass
But after finishing to install cartodb I can not insert a user with Requet sh script / create_dev_user $ {} SUBDOMAIN

Here is the error that returns me:

[pool] Found a connection for localhost:cartodb_dev_user_2d642ffd-f761-4017-8c0f-60b80b1e94c0_db:5432:postgres:sequel (4)
(0.000079s) BEGIN
(0.000125s) GRANT CONNECT ON DATABASE "cartodb_dev_user_2d642ffd-f761-4017-8c0f-60b80b1e94c0_db" TO "publicuser"
(0.000487s) COMMIT
[pool] Found a connection for localhost:cartodb_dev_user_2d642ffd-f761-4017-8c0f-60b80b1e94c0_db:5432:postgres:sequel (4)
(0.000080s) BEGIN
(0.000103s) GRANT USAGE ON SCHEMA "cartodb" TO "publicuser"
(0.005637s) GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "cartodb" TO "publicuser"
(0.000213s) GRANT SELECT ON ALL TABLES IN SCHEMA "cartodb" TO "publicuser"
(0.000097s) REVOKE ALL ON TABLE cartodb.CDB_CONF FROM "publicuser"
(0.001397s) COMMIT
[pool] Found a connection for localhost:cartodb_dev_user_2d642ffd-f761-4017-8c0f-60b80b1e94c0_db:5432:postgres:sequel (4)
(0.000076s) BEGIN
(0.000137s) REVOKE SELECT ON cartodb.cdb_tablemetadata FROM publicuser CASCADE
(0.000141s) REVOKE SELECT ON cartodb.cdb_analysis_catalog FROM publicuser CASCADE
(0.000984s) COMMIT
[pool] Found a connection for localhost:cartodb_dev_user_2d642ffd-f761-4017-8c0f-60b80b1e94c0_db:5432:postgres:sequel (4)
(0.000055s) BEGIN
(0.000091s) GRANT USAGE ON SCHEMA public TO publicuser
(0.042562s) GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO publicuser
(0.000157s) GRANT SELECT ON spatial_ref_sys TO publicuser
(0.006940s) COMMIT
[pool] Found a connection for localhost:cartodb_dev_user_2d642ffd-f761-4017-8c0f-60b80b1e94c0_db:5432:postgres:sequel (4)
(0.001234s) REVOKE ALL ON TABLE cartodb.CDB_CONF FROM "development_cartodb_user_2d642ffd-f761-4017-8c0f-60b80b1e94c0"
[pool] Found a connection for localhost:cartodb_dev_user_2d642ffd-f761-4017-8c0f-60b80b1e94c0_db:5432:postgres:sequel (4)
(0.000997s) REVOKE ALL ON TABLE cartodb.CDB_CONF FROM "publicuser"
ETHON: Libcurl initialized
ETHON: performed EASY effective_url=http://gravatar.com/avatar/981ebcd7f1927fffe9ebae704edadb88?s=128&d=http://404 response_code=302 return_code=ok total_time=0.281372
(0.001063s) ROLLBACK
rake aborted!
No such file or directory @ rb_sysopen - /home/diallo/cartodb/log/http_client.log
/usr/lib/ruby/2.2.0/open-uri.rb:36:in `initialize'
/usr/lib/ruby/2.2.0/open-uri.rb:36:in `open'
/usr/lib/ruby/2.2.0/open-uri.rb:36:in `open'
/usr/lib/ruby/2.2.0/logger.rb:636:in `create_logfile'
/usr/lib/ruby/2.2.0/logger.rb:630:in `rescue in open_logfile'
/usr/lib/ruby/2.2.0/logger.rb:627:in `open_logfile'
/usr/lib/ruby/2.2.0/logger.rb:584:in `initialize'
/usr/lib/ruby/2.2.0/logger.rb:318:in `new'
/usr/lib/ruby/2.2.0/logger.rb:318:in `initialize'
/var/lib/gems/2.2.0/gems/activesupport-3.2.22/lib/active_support/core_ext/logger.rb:72:in `initialize'
/home/diallo/cartodb/lib/carto/http/response_logger.rb:35:in `new'
/home/diallo/cartodb/lib/carto/http/response_logger.rb:35:in `logger'
/home/diallo/cartodb/lib/carto/http/response_logger.rb:31:in `log'
/home/diallo/cartodb/lib/carto/http/request.rb:24:in `run'
/home/diallo/cartodb/app/models/user.rb:718:in `reload_avatar'
/home/diallo/cartodb/app/models/user.rb:708:in `load_avatar'
/home/diallo/cartodb/app/models/user.rb:250:in `after_create'
/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1585:in `block (2 levels) in _save'
/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:867:in `around_create'
/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1578:in `block in _save'
/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:867:in `around_save'
/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1573:in `_save'
/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1254:in `block (2 levels) in save'
/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1722:in `block in checked_transaction'
/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/database/query.rb:323:in `_transaction'
/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/database/query.rb:285:in `block in transaction'
/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `block in synchronize'
/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/database/connecting.rb:236:in `synchronize'
/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/database/query.rb:278:in `transaction'
/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1722:in `checked_transaction'
/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1254:in `block in save'
/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1713:in `checked_save_failure'
/var/lib/gems/2.2.0/gems/sequel-3.42.0/lib/sequel/model/base.rb:1254:in `save'
/home/diallo/cartodb/lib/tasks/setup.rake:74:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/var/lib/gems/2.2.0/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => cartodb:db:create_dev_user

**Comment by jgoizueta** [comment]
@Baguewi the problem seems to be here, where a log file cannot be opened. Check if the directory `/home/diallo/cartodb/log` exists.

```
No such file or directory @ rb_sysopen - /home/diallo/cartodb/log/http_client.log
/usr/lib/ruby/2.2.0/open-uri.rb:36:in `initialize'
/usr/lib/ruby/2.2.0/open-uri.rb:36:in `open'
/usr/lib/ruby/2.2.0/open-uri.rb:36:in `open'
/usr/lib/ruby/2.2.0/logger.rb:636:in `create_logfile'
/usr/lib/ruby/2.2.0/logger.rb:630:in `rescue in open_logfile'
/usr/lib/ruby/2.2.0/logger.rb:627:in `open_logfile'
/usr/lib/ruby/2.2.0/logger.rb:584:in `initialize'
/usr/lib/ruby/2.2.0/logger.rb:318:in `new'
/usr/lib/ruby/2.2.0/logger.rb:318:in `initialize'
/var/lib/gems/2.2.0/gems/activesupport-3.2.22/lib/active_support/core_ext/logger.rb:72:in `initialize'
/home/diallo/cartodb/lib/carto/http/response_logger.rb:35:in `new'
/home/diallo/cartodb/lib/carto/http/response_logger.rb:35:in `logger'
/home/diallo/cartodb/lib/carto/http/response_logger.rb:31:in `log'
/home/diallo/cartodb/lib/carto/http/request.rb:24:in `run'
/home/diallo/cartodb/app/models/user.rb:718:in `reload_avatar'
/home/diallo/cartodb/app/models/user.rb:708:in `load_avatar'
/home/diallo/cartodb/app/models/user.rb:250:in `after_create'
```

**Comment by jgoizueta** [comment]
Of course, the problem now doesn't seem related to this SQL extension, so if you cannot solve it you may want to open a ticket in the https://github.com/CartoDB repo.

In any case, thanks for sharing the details of your problem, @Baguewi

**Comment by Baguewi** [comment]
@jgoizueta Actually the /home/diallo/cartodb/log did not exist, I add the directory with the mkdir command and I managed to insert my user.

Thank you for your help.

**Comment by Baguewi** [comment]
@
