### ISSUE TITLE
Data import CSV file

### ISSUE THREAD

**Issue by Baguewi** [CartoDB/cartodb-postgresql#282]
Hello if someone can help me.
I had installed CartoDB locally on my Ubuntu 14.04 and the installation was perfect. I can create dataset by CartoDB's GUI and able to visulaize data perfectly without any problem. But when i drag and drop a csv or geojson file externally from my system, it is throwing an error as below

Rails: 
![73d1b0b0-914e-11e6-92dd-c079c7c2d7fe](https://cloud.githubusercontent.com/assets/10731720/19387560/38e652bc-921b-11e6-8386-8c675ddfa741.png)

And my CartoDb's UI is showing

1 An unknown error has happened

Persisting error? Please send us the following code:
01f18226-a811-4992-84b5-8c2143ca4088

if I run the tests in my repertoire cartodb the results of tests gives me the following results
![047bb8e2-9152-11e6-9395-f33e91e9395e](https://cloud.githubusercontent.com/assets/10731720/19387569/48971232-921b-11e6-99b9-bfc86a9cb81c.png)

**Comment by Algunenano** [comment]
Unrelated to this project
