### ISSUE TITLE
Support Polygon and Line overviews

### ISSUE THREAD

**Issue by jaakla** [CartoDB/cartodb-postgresql#289]
Required to avoid too large vector tiles in lower zoom levels. Should do line simplification with given parameter tolerance and strategy (default DouglasPeucker, but certain datasets need different one). 

Alternative would be to do automatic simplification in vector tile generator ("renderer") level. Overview approach would make rendering faster, and there would be simplification tuning options. 

Complex cases like simplification of river polygons to lines might come later.

**Comment by Algunenano** [comment]
Stale. For MVTs this is already handled by ST_AsMVTGeom
