### ISSUE TITLE
0.18.5 DigitSeparatorTest ... FAILED

### ISSUE THREAD

**Issue by kiwibrew** [CartoDB/cartodb-postgresql#292]
Followed build instructions here: http://cartodb.readthedocs.io/en/latest/install.html
on a clean "12.04.5 LTS, Precise Pangolin"
Executing "sudo PGUSER=postgres make installcheck" results in 22/23 tests passing

Test that fails is test/CDB_DigitSeparatorTest. Any help would be much appreciated!

_**/home/jonathanbrewer/cartodb-postgresql/regression.diffs**_

```
*** /home/jonathanbrewer/cartodb-postgresql/expected/test/CDB_DigitSeparatorTest.out	2017-01-12 23:01:35.202029554 +0000
--- /home/jonathanbrewer/cartodb-postgresql/results/test/CDB_DigitSeparatorTest.out	2017-01-12 23:11:56.862029653 +0000
***************
*** 1,6 ****
--- 1,7 ----
  \set ECHO none
  BEGIN
  CREATE TABLE
+ COPY 3
  none||
  only_com_dec|.|,
  only_dot_dec|,|.

======================================================================

```
**_/home/jonathanbrewer/cartodb-postgresql/regression.out_**

```
test test_setup               ... ok
test test/CDB_AnalysisCheckTest ... ok
test test/CDB_CartodbfyTableTest ... ok
test test/CDB_DateToNumberTest ... ok
test test/CDB_DigitSeparatorTest ... FAILED
test test/CDB_DistinctMeasureTest ... ok
test test/CDB_DistTypeTest    ... ok
test test/CDB_EqualIntervalBinsTest ... ok
test test/CDB_GreatCircle     ... ok
test test/CDB_HeadsTailsBinsTest ... ok
test test/CDB_HelperTest      ... ok
test test/CDB_HexagonTest     ... ok
test test/CDB_JenksBinsTest   ... ok
test test/CDB_MathTest        ... ok
test test/CDB_OverviewsTest   ... ok
test test/CDB_QuantileBinsTest ... ok
test test/CDB_QueryStatementsTest ... ok
test test/CDB_QueryTablesTest ... ok
test test/CDB_QuotaTest       ... ok
test test/CDB_StatsTest       ... ok
test test/CDB_TransformToWebmercatorTest ... ok
test test/CDB_UserTablesTest  ... ok
test test/CDB_XYZ_ExtentTest  ... ok
```

**Comment by kiwibrew** [comment]
I've had a look around at what's going on.

First I created the CDB_DigitSeparator function defined in https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_DigitSeparator.sql which works just fine.

The actual failing test is here: https://github.com/CartoDB/cartodb-postgresql/blob/master/test/CDB_DigitSeparatorTest.sql so I decided to step through it manually.

`
postgres=# BEGIN;
BEGIN
postgres=# CREATE TEMP TABLE "_CDB_DigitSeparatorTest" (
postgres(#   none text,
postgres(#   only_com_dec text,
postgres(#   only_dot_dec text,
postgres(#   only_com_tho text,
postgres(#   only_dot_tho text,
postgres(#   both_com_dec text,
postgres(#   both_dot_dec text,
postgres(#   "only_com_AMB" text,
postgres(#   "only_dot_AMB" text
postgres(# );
CREATE TABLE
postgres=# COPY "_CDB_DigitSeparatorTest" FROM STDIN;
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself.
>> 123456	123,1235	123.12345	1,234,231	1.234.234	1.234,23	1,234.23	1,123	1.123
>> 123456	123,12	123.12	231	234	1.121.234,230	3,111,234.230	123,123	123.123
>> 123456	123,12	123.12	231	234	1.121.234,2	3,111,234.230	123,123	123.123
>> \.
COPY 3
postgres=# SELECT 'none', * FROM
postgres-#        CDB_DigitSeparator('"_CDB_DigitSeparatorTest"'::regclass, 'none');
 ?column? | t | d
----------+---+---
 none     |   |
(1 row)

postgres=# SELECT 'only_com_dec', * FROM
postgres-#        CDB_DigitSeparator('"_CDB_DigitSeparatorTest"'::regclass, 'only_com_dec');
   ?column?   | t | d
--------------+---+---
 only_com_dec | . | ,
(1 row)

postgres=# SELECT 'only_dot_dec', * FROM
postgres-#        CDB_DigitSeparator('"_CDB_DigitSeparatorTest"'::regclass, 'only_dot_dec');
   ?column?   | t | d
--------------+---+---
 only_dot_dec | , | .
(1 row)

postgres=# SELECT 'only_com_tho', * FROM
postgres-#        CDB_DigitSeparator('"_CDB_DigitSeparatorTest"'::regclass, 'only_com_tho');
   ?column?   | t | d
--------------+---+---
 only_com_tho | , | .
(1 row)

postgres=# SELECT 'only_dot_tho', * FROM
postgres-#        CDB_DigitSeparator('"_CDB_DigitSeparatorTest"'::regclass, 'only_dot_tho');
   ?column?   | t | d
--------------+---+---
 only_dot_tho | . | ,
(1 row)

postgres=# SELECT 'both_com_dec', * FROM
postgres-#        CDB_DigitSeparator('"_CDB_DigitSeparatorTest"'::regclass, 'both_com_dec');
   ?column?   | t | d
--------------+---+---
 both_com_dec | . | ,
(1 row)

postgres=# SELECT 'both_dot_dec', * FROM
postgres-#        CDB_DigitSeparator('"_CDB_DigitSeparatorTest"'::regclass, 'both_dot_dec');
   ?column?   | t | d
--------------+---+---
 both_dot_dec | , | .
(1 row)

postgres=# SELECT 'only_com_AMB', * FROM
postgres-#        CDB_DigitSeparator('"_CDB_DigitSeparatorTest"'::regclass, 'only_com_AMB');
   ?column?   | t | d
--------------+---+---
 only_com_AMB |   |
(1 row)

postgres=# SELECT 'only_dot_AMB', * FROM
postgres-#        CDB_DigitSeparator('"_CDB_DigitSeparatorTest"'::regclass, 'only_dot_AMB');
   ?column?   | t | d
--------------+---+---
 only_dot_AMB |   |
(1 row)`
The DigitSeparatorTest that fails expects to see results per this file: https://github.com/CartoDB/cartodb-postgresql/blob/master/test/CDB_DigitSeparatorTest_expect

What we're actually seeing is:

`
BEGIN
CREATE TABLE
COPY 3
none     |   |
only_com_dec | . | ,
only_dot_dec | , | .
only_com_tho | , | .
only_dot_tho | . | ,
both_com_dec | . | ,
both_dot_dec | , | .
only_com_AMB |   |
only_dot_AMB |   |
DROP TABLE
COMMIT
`

The test is passing just fine, but the expected results file doesn't include the response from entering data into the table "COPY 3" so the test is failing.

@strk at first glance it seems to me everything will be ok if you update the CDB_DigitSeparatorTest_expect

**Comment by Algunenano** [comment]
Should be ok now
