### ISSUE TITLE
Schema changes in user dbs do not trigger invalidation

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb-postgresql#293]
Schema changes on user tables do not execute the invalidation trigger, meaning that after adding a column to a table using the SQL API, running a `SELECT *` does not return the new columns.

STR:
- Create a table
- Run `SELECT * FROM table`
- Run `ALTER TABLE table ADD COLUMN wadus int`
- Run `SELECT * FROM table`

Currently, you get the table without the new column, until you do an insert/update or the cache expires.

cc @rochoa @rafatower (Should we be pinging you on all #engine related issues for prioritization? What works best for you?)

**Comment by rochoa** [comment]
This is an old friend, but let's use this as the issue to track it.

This supersedes https://github.com/CartoDB/cartodb/issues/11114.

References: https://github.com/CartoDB/pg_schema_triggers/issues/4.

**Comment by javitonino** [comment]
Oh, I didn't think to search in the cartodb repo. Sorry for the duplicate!

**Comment by Algunenano** [comment]
No longer a thing.
