### ISSUE TITLE
why do we need plpythonu extension

### ISSUE THREAD

**Issue by drzhouq** [CartoDB/cartodb-postgresql#294]
It seems to me that only a few functions  require the plpythonu extension for performance reasons. I am wondering whether we can rewrite those in PL/Java instead.  Because Amazon AWS RDB does not support plpythonu because of security concern, it would be nice to have those functions rewritten in Java.

**Comment by radumas** [comment]
@drzhouq, have you tried installing this on an RDS? I was wondering to what degree functionality is impacted if you just create the sql functions without anything that requires python

**Comment by drzhouq** [comment]
No, I haven't. RDS does not allow python language (still). I never had time (or too lazy) to look into those functions and rewrite it in PL. One of those days, I might be cornered to do this. I will update you when that happens.

**Comment by Algunenano** [comment]
The extension uses plpythonu to open http connections, which is unsafe by nature.
