### ISSUE TITLE
Create function CDB_EstimateRowCount(query text)

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb-postgresql#295]
### Description

Add a new function to `cartodb` extension to be called `CDB_EstimateRowCount(query text)`.

The purpose of that function is, given a query, to return a row count estimate that is suitable for quota usage estimation.

Example of its usage:
```sql
SELECT CDB_EstimateRowCount($$
  UPDATE addresses SET the_geom = cdb_geocode_street_point(addr, city, state, 'US');
$$) AS row_count;

 row_count 
-----------
         5
(1 row)
```

What the function should do:
1. Get the list of tables affected by the query
1. Make sure stats exist for all of them, otherwise execute `ANALYZE` to get them.
1. Use `EXPLAIN` to get a row count estimate of the query.

### Implementation notes
* The list of affected tables can be get by using [CDB_QueryTablesText](https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_QueryTables.sql)
* The view `pg_stat_user_tables` is a convenient place to look for stats.
* There's still a corner case with *fresh empty tables* that we don't aim to solve here. See [this](https://github.com/postgres/postgres/blob/18dc2aee5f303447bef48dee596a664d90f6939a/src/backend/optimizer/util/plancat.c#L915-L951)

**Comment by jgoizueta** [comment]
For reference, see this JS implementation: https://github.com/CartoDB/camshaft/blob/054fb088ffdae8f3e89c455ebff12dd323ca6693/lib/limits/estimates.js#L27-L38

**Comment by jgoizueta** [comment]
PR here: https://github.com/CartoDB/cartodb-postgresql/pull/298

**Comment by jgoizueta** [comment]
Acceptance could be checked in staging, installing the branch and updating the cartodb-extension for some user.

Things to check:
* For a newly created table with some rows inserted the estimate `CDB_EstimateRowCount('select * from table')` should be accurate. Also: for a fresh table with no stats, after calling `CDB_EstimateRowCount` stats should be present.
* For a newly created empty table an estimation (albeit not accurate) should be obtained (typically 850 rows).
* For older populated tables some sensible estimation should be obtained
* It should return a reasonable estimate for filtered queries
* It should work for org user tables. Extra bonus: check with org username containing a hyphen.
* It should fail with an error with an invalid query

**Comment by jgoizueta** [comment]
Acceptance was successful in staging; moving on to deploy in production

**Comment by jgoizueta** [comment]
Deployment almost done, I'll finish tomorrow updating the extension version in all the users databases.

**Comment by jgoizueta** [comment]
Deployed in production; all user SAAS databases upgraded to version 0.19.0 of the extension which includes the new function.
