### ISSUE TITLE
Maybe we should use INMUTABLE in CDB_QueryTablesText

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb-postgresql#299]
Working on the base maps logs I've seen that we use the `cdb_querytablestext` a lot and I've noticed that the function is created as `VOLATILE` so we're not doing any possible optimization. Is this a conscious decision or we can move it to `IMMUTABLE` or `STABLE` so we could save some query time?

I've checked the base maps logs to count the number of queries and these are the numbers:
```
ubuntu@cdb-dev:~/www/cartodb/misc/basemaps_research/logs/production/dbdf31$ grep -i 'CDB_QueryTablesText' postgresql_parsed_log.log | wc -l
497346
ubuntu@cdb-dev:~/www/cartodb/misc/basemaps_research/logs/production/dbdf31$ grep -i 'CDB_QueryTablesText' rest_log_file.log | wc -l
21821
```
about 520k calls to that funcion from `2017-04-18 22:17:08` to `2017-04-27 16:04:01`

Checking the duration of the query goes from 0.8 ms to 100ms in the case of the overviews so maybe the saved time is not huge but could help. I don't know is just something comes to my mind.

// @javisantana @rochoa @rafatower

**Comment by direvus** [comment]
It is definitely not IMMUTABLE -- the results of the function depend on parsing the output of EXPLAIN, which output will vary depending on the tables and indexes available to be queried.  A function is only IMMUTABLE if it is guaranteed to always return the same results given the same inputs.

You could possibly make an argument for STABLE.  I don't think there are any side-effects in the function and there should not be any changes within the context of a single statement.

**Comment by rochoa** [comment]
Thanks, @direvus.

A few months ago, @Algunenano worked on https://github.com/CartoDB/cartodb-postgresql/pull/312 to add the right information to almost all functions. He already checked `CDB_QueryTablesText`.
