### ISSUE TITLE
mark functions as parallel

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb-postgresql#300]
Using any function from this extension makes postgres (>=9.6) planner unhappy because it can't paralelize anything.

We should mark functions as parallel when possible (for example cdb_xyz_* family)

https://www.postgresql.org/docs/current/static/parallel-safety.html

It should be also compatible with postgres 9.5. (it worths checking postgis way to do this: https://github.com/postgis/postgis/blob/bd3177743db5cb786deb05d7327f39a5cec2daf6/postgis/sqldefines.h.in#L17)

**Comment by pramsey** [comment]
Almost everything can be marked parallel. If it doesn't read from a table, it can be marked.

**Comment by Algunenano** [comment]
I've been working on this in #312 and right now it's at least building and passing tests in 9.5 (no parallel) and 10. I'm not completely happy about how the version is handled (grepping out PARALLEL when it isn't supported) but I prefer it to generating all sql files from .in with configure just for this.

I've added PARALLEL in all functions although PARALLEL UNSAFE could be omitted to make sure all functions are properly tagged. Same for  VOLATILE/STABLE/IMMUTABLE (should address #299 too).
It's still under testing but I hope it's a nice initial approach.

**Comment by Algunenano** [comment]
I've been testing this with an up to date release of Builder and I haven't seen any issue. Also, I haven't seen any measurable improvement yet and I think this is due two factors:
- Analysis queries are not properly marked yet (https://github.com/CartoDB/crankshaft/issues/181).
- Aggregation queries are not really efficient nor parallelizable, for example the 
 query for SQUARES aggregations times out just calculating all possible squares at certain zoom level (https://github.com/CartoDB/cartodb-postgresql/issues/314)

**Comment by pramsey** [comment]
Be careful with sprinkling VOLATILE around, it's only for places where two runs of the same function with the same parameters might result in different results (function depends on other tables, usually).

**Comment by Algunenano** [comment]
You are right, but keep in mind that VOLATILE is the default when it's not declared so I don't expect it'd have any impact; it's just a way for explain that we have reviewed the functions and they are indeed volatile, which helps categorize other functions that use them or if we decide to change the implementation to make them IMMUTABLE (if possible).

The main factors I've seen to having to declare a function as VOLATILE have been modifying the database, executing a query passed as a parameter (string) and, in some cases, using random().

**Comment by Algunenano** [comment]
Merged and deployed as https://github.com/CartoDB/cartodb-postgresql/releases/tag/0.20.0
