### ISSUE TITLE
[Overviews] Usage of quote_ident makes use of schema in strategy functions

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb-postgresql#303]
We're using [quote_ident](https://www.postgresql.org/docs/9.5/static/functions-string.html#FUNCTIONS-STRING-OTHER) to surround with quotes strings passed as parameters when they're needed [here](https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_Overviews.sql#L1088) and [here](https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_Overviews.sql#L1106).

The problem with this approach is that if we have functions that we need to use the schema, the function `schema.table_name` is take as the table name and quoted and we can't call it.

For example:

```
cartodb_dev_user_f72afc82-da27-4651-bac7-99609e4106cb_db=# select
cdb_createoverviews('etherfree3.hotspots_full','etherfree3._cdb_dumb_z16_strategy'::regproc, 
'_CDB_Sampling_Reduce_Strategy(REGCLASS,INTEGER,INTEGER,FLOAT8,BOOLEAN)'::regprocedur
e);                         
ERROR:  42883: function etherfree3._cdb_dumb_z16_strategy(unknown, integer) 
does not exist  LINE 1: SELECT "etherfree3._cdb_dumb_z16_strategy"('etherfree3.hotsp...                                                                                ^
```

**Comment by Algunenano** [comment]
Stale
