### ISSUE TITLE
[Overviews] CDB_Sampling_Reduce_Strategy returning fewer samples that should

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb-postgresql#304]
@jgoizueta found an issue with _CDB_Sampling_Reduce_Strategy. It uses CDB_RandomTids, which samples by skipping pages.

Since overviews are created in cascade, each level from the next (higher zoom) one, [and now the overview tables are reused deleting its rows (not truncating to avoid locking)](https://github.com/CartoDB/cartodb-postgresql/pull/302), the first time an overview table has been reused half of its pages are empty, the second time 2/3 etc.

The sampling strategy used by CDB_RandomTids expects rows regularly distributed over pages, and degrades (the number of sampled rows is increasingly reduced) as more and more rows are deleted.

We could fix this, with a plain VACUUM, which does not lock, but it cannot be executed from a function 😞  `ERROR: VACUUM cannot be executed from a function or multi-command string`

So I would avoid CDB_RandomTids and use a simplistic random() sampling, which is more inefficient but I think _CDB_Sampling_Reduce_Strategy is probably not used by anybody...

**Comment by Algunenano** [comment]
Stale
