### ISSUE TITLE
Unique identifier generation can break CDB_CartodbfyTable

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb-postgresql#305]
The way we generate unique identifiers can cause trouble to the client code, such as `CDB_CartodbfyTable`, because it can rapidly exhaust the space of names it is able to generate.

The real-world scenario we found is a user creating empty layers and then renaming them.

That scenario can be reproduced with this script:
```plpgsql
DO $$
BEGIN
   FOR i IN 1..101 LOOP
        EXECUTE 'CREATE TABLE untitled_table();';
        EXECUTE $query$SELECT CDB_CartodbfyTable('untitled_table');$query$;
        EXECUTE 'ALTER TABLE untitled_table RENAME TO my_renamed_table_' || i;
   END LOOP;
END;
$$;
```

which breaks with this error:
```
ERROR:  CDB(_CDB_Unique_Identifier): looping too far
CONTEXT:  SQL statement "SELECT _CDB_Error('looping too far', '_CDB_Unique_Identifier')"
PL/pgSQL function _cdb_unique_identifier(text,text,text,text) line 53 at PERFORM
PL/pgSQL function _cdb_rewrite_table(regclass,text) line 117 at assignment
SQL statement "SELECT _CDB_Rewrite_Table(reloid, destschema)"
PL/pgSQL function cdb_cartodbfytable(text,regclass) line 51 at PERFORM
PL/pgSQL function cdb_cartodbfytable(regclass) line 3 at RETURN
SQL statement "SELECT CDB_CartodbfyTable('untitled_table');"
PL/pgSQL function inline_code_block line 5 at EXECUTE
```

Here's the code generating the unique identifiers: https://github.com/CartoDB/cartodb-postgresql/blob/091aea088e1d37290dbac9d602256d0ececd50bb/scripts-available/CDB_Helper.sql#L34-L58

and here how it is used from the cartodbfy'ation process: https://github.com/CartoDB/cartodb-postgresql/blob/208ebb272447520357b1553e35462293cfb84dbd/scripts-available/CDB_CartodbfyTable.sql#L902-L907

**Comment by rafatower** [comment]
Here's my proposal:
- create a sequence to generate unique identifiers, within the extension and owned by the extension.
- compose the identifier as `prefix + _seqid`, trimming the prefix length to not surpass the 63 bytes identifier limit.

Sequences can generate numbers up to `9223372036854775807` which is long enough to make sure there will be no collisions. That figure is 19 chars long, if we add a 4 letter suffix `_seq`, that leaves `63 - 4 - 19 = 40` characters for meaningful names, which shall be enough.

Having a meaningful name shall not be a priority, as the table/column owning the sequence can always be recovered from the catalog.

**Comment by jgoizueta** [comment]
Another proposal to avoid having to create the sequence: use a non-iterative, non-limited function to add a distinct numeric prefix like this (and trimming from the left to stay within 63 chars):

```SQL
CREATE OR REPLACE FUNCTION cartodb._CDB_Unique_Identifier(prefix TEXT, relname TEXT, suffix TEXT, schema TEXT DEFAULT NULL)
RETURNS TEXT
AS $$
DECLARE
  maxlen CONSTANT INTEGER := 63;

  rec RECORD;
  usedspace INTEGER;
  ident TEXT;
  escaped_ident TEXT;
  candrelname TEXT;
  max_counter INTEGER;
  i INTEGER;
BEGIN
  -- Accounts for the _XX incremental suffix in case the identifier is taken
  usedspace := 3;
  usedspace := usedspace + coalesce(octet_length(prefix), 0);
  usedspace := usedspace + coalesce(octet_length(suffix), 0);

  candrelname := _CDB_Octet_Truncate(relname, maxlen - usedspace);

  IF candrelname = '' THEN
    PERFORM _CDB_Error('prefixes are to long to generate a valid identifier', '_CDB_Unique_Identifier');
  END IF;

  ident := coalesce(prefix, '') || candrelname || coalesce(suffix, '');

  IF schema IS NOT NULL THEN
    SELECT c.relname, n.nspname
    INTO rec
    FROM pg_class c
    JOIN pg_namespace n ON c.relnamespace = n.oid
    WHERE c.relname = ident
    AND n.nspname = schema;
  ELSE
    SELECT c.relname, n.nspname
    INTO rec
    FROM pg_class c
    JOIN pg_namespace n ON c.relnamespace = n.oid
    WHERE c.relname = ident;
  END IF;

  IF NOT FOUND THEN
    RETURN ident;
  END IF;

  SELECT replace(ident, '_', '#_') INTO escaped_ident;

  IF schema IS NOT NULL THEN
    -- Sadly the substring(... FROM ... FOR '#') form with an escape character doesn't return
    -- the parenthesized subexpresion as the two parameter form does.
    SELECT MAX(substring(c.relname FROM ident || '_([0-9]+)')::int)
    INTO max_counter
    FROM pg_class c
    JOIN pg_namespace n ON c.relnamespace = n.oid
    WHERE c.relname SIMILAR TO escaped_ident || '#_[0-9]+' ESCAPE '#'
    AND n.nspname = schema;
  ELSE
    SELECT MAX(substring(c.relname FROM ident || '_([0-9]+)')::int)
    INTO max_counter
    FROM pg_class c
    JOIN pg_namespace n ON c.relnamespace = n.oid
    WHERE c.relname SIMILAR TO escaped_ident || '#_[0-9]+' ESCAPE '#';
  END IF;

  RETURN ident || '_' || (max_counter + 1)::text;
END;
$$ LANGUAGE 'plpgsql';
```

I admit this is uglier than the other solution.... 🤔 and maybe we can create (if not exists) the needed sequence inside function to generate unique identifier, in which case probably that approach is the winner.

**Comment by rafatower** [comment]
Anyway mine would not work cause we cannot make assumptions about existing identifiers.

**Comment by rafatower** [comment]
Here's how postgres does it internally:

https://github.com/postgres/postgres/blob/113b0045e20d40f726a0a30e33214455e4f1385e/src/backend/parser/parse_utilcmd.c#L427

https://github.com/postgres/postgres/blob/08aed6604de2e6a9f4d499818d7c641cbf5eb9f7/src/backend/commands/indexcmds.c#L1579

funny enough, they use an infinite loop. I think the most cost-effective solution is just to raise the search space size to 1000 or 10000 and that's it.

**Comment by rafatower** [comment]
PR here: https://github.com/CartoDB/cartodb-postgresql/pull/306
