### ISSUE TITLE
Check how we manage PK sequences in cartodbfy

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb-postgresql#318]
As per @pramsey it seems like we're creating sequences for cartodbfy'ed tables without taking into account ownership. If that is the case, the sequences will be left all over the place when deleting tables.

We should fix it for the sake of housekeeping. Mind that a large number of dangling objects in the catalog may impact performance.

**Comment by pramsey** [comment]
I'm wrong, we do set ownership (though maybe we once didn't? ogr2ogr didn't? anyways I had some orphan sequences, but in general the tables in my account *do* set ownership. Also, though there was a bug, it was really all ogr2ogr's fault. There's one tweak we could make, I'll do a little PR for discussion, it's cosmetic.

**Comment by Algunenano** [comment]
Is this still necessary? Seems that @pramsey confirmed this isn't an issue but I could have a look if required.

**Comment by rafatower** [comment]
Not for RT but to take into account when adding the COPY to GDAL, to take advantage of it to clean up accesses to catalog and metadata that can be avoided in the driver.

**Comment by pramsey** [comment]
Let's shut this one down, I think it happened, but perhaps related to 3rd party tools, or in the distant past.
