### ISSUE TITLE
Publish cartodb repo commit along with the release notes

### ISSUE THREAD

**Issue by jvillarf** [CartoDB/cartodb-postgresql#324]
## Description
Hello :hugs: ,

this is just a friendly request: we are now working in the new **onpremises-2.2.0** release using **omnibus** to compile every **carto** componente from sources. It turns out, we were installing **cartodb-postgresql extension 0.21.0**, but our builder version was pointing to `v4.11.38` which doesn't include **postgresql extension 0.21.0 version**. Of course, we should have reviewed it carefully, but we were wondering if you could include the **cartodb repo tag** where the extension was published, along with the **postgresql extension release notes**.

Thanks a lot.

@rafatower @jgoizueta 

cc/  @dppascual

**Comment by jvillarf** [comment]
**Related ticket**: https://github.com/CartoDB/onpremises/issues/450

**Comment by rafatower** [comment]
If you picked master of `cartodb`, you may have had the bad chance of picking the "wrong version" between the changes in `cartodb-postgresql` and `cartodb` repositories. If you picked `v4.11.38` I don't really understand what could've happened.

As part of the process of deploying a new version, as described in the [docs](https://github.com/CartoDB/doc-internal/blob/master/tech-internals/source/platform/internal_architecture/services/postgresql/extensions/deploy_cartodb_postgresql_extension.rst) , the master `cartodb-postgresql` can be ahead of the master of `cartodb` for a short window. Anyway it is impossible to update and tag both repos synchronously.

That said, you can always pick the exact version in sync with the `cartodb` repository just by checking the subrepository commit hash / tag:
```
$ git checkout v4.11.38
M       lib/sql
Note: checking out 'v4.11.38'.

$ git submodule init && git submodule update
Submodule path 'lib/sql': checked out '8131887204e76722a2ebda01b0ab5acee7abc911'

$ git grep 0.20.0 -- "*.rb"
app/controllers/home_controller.rb:  CDB_LATEST_VERSION = '0.20.0'.freeze
app/models/user/db_service.rb:          cdb_extension_target_version = '0.20.0'

$ cd lib/sql/
$ git describe 
0.20.0
```

So in the case of carto `v4.11.38` you should have picked the extension `0.20.0`.

HTH

**Comment by jvillarf** [comment]
Thanks for the feedback @rafatower , we'll make sure in the next release, we don't perform the checks above in advance :ok_hand:
