### ISSUE TITLE
installcheck failed with GreatCircle & OverviewTest

### ISSUE THREAD

**Issue by casbie** [CartoDB/cartodb-postgresql#336]
I followed the instructions to install cartodb-postgresql but have two fails while doing installcheck.
My OS version is Ubuntu 16.04 and I use the branch with tag 0.23.2

`test test/CDB_GreatCircle     ... FAILED`
`test test/CDB_OverviewsTest   ... FAILED`

I read the diff file but still not understand what causes the test fail.
The diff file is as the following:
[regression.diffs.txt](https://github.com/CartoDB/cartodb-postgresql/files/2230268/regression.diffs.txt)

And I tried to diff the expected file and result file.

## CDB_GreatCircle
The output seems to be pairs of numbers, so I try to compare the result by pairs.
But apparently, the outputs from the result and the expected file are almost different.

## CDB_OverviewsTest
It seems like there are more column names returned than expected.

I extracted some diff output as the following:

`diff expected/test/CDB_OverviewsTest.out results/test/CDB_OverviewsTest.out`
```
< {_vovw_2_base_bare_t,_vovw_1_base_bare_t,_vovw_0_base_bare_t}
---
> {_vovw_23_base_bare_t,_vovw_22_base_bare_t,_vovw_21_base_bare_t,_vovw_20_base_bare_t,_vovw_19_base_bare_t,_vovw_18_base_bare_t,_vovw_17_base_bare_t,_vovw_16_base_bare_t,_vovw_15_base_bare_t,_vovw_14_base_bare_t,_vovw_13_base_bare_t,_vovw_12_base_bare_t,_vovw_11_base_bare_t,_vovw_10_base_bare_t,_vovw_9_base_bare_t,_vovw_8_base_bare_t,_vovw_7_base_bare_t,_vovw_6_base_bare_t,_vovw_5_base_bare_t,_vovw_4_base_bare_t,_vovw_3_base_bare_t,_vovw_2_base_bare_t,_vovw_1_base_bare_t,_vovw_0_base_bare_t}
```

Thank you!

**Comment by Algunenano** [comment]
Should be fixed with https://github.com/CartoDB/cartodb-postgresql/pull/339. Thanks!
