### ISSUE TITLE
Add DROP function to the artifact in order to avoid migration problems

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb-postgresql#341]
When we create a new version we don't add the DROP to functions that have been removed creating a problem when we try to migrate clients with those old functions.

**Comment by Algunenano** [comment]
Unless we've forgotten about it somewhere we are already doing this ([example](https://github.com/CartoDB/cartodb-postgresql/pull/340/files#diff-abaa85f717a1afdd6b0680a776aed39aR149).

Do you have a list of troublesome functions so we add the drop?

**Comment by ethervoid** [comment]
Yep, old ones. We have migration problems with the DDL old functions:

```
cdb_handle_create_table()
cdb_handle_drop_table()
cdb_handle_alter_column()
cdb_handle_drop_column()
cdb_handle_add_column()
cdb_disable_ddl_hooks()
cdb_enable_ddl_hooks()
```

I'm pretty sure they're not in the current versions right now but this ticket was more like a suggestion if we're not doing it :)

**Comment by javitonino** [comment]
cc @CartoDB/rt-managers (we have replaced #343 for this one)
