### ISSUE TITLE
Errors on InstallCheck

### ISSUE THREAD

**Issue by AnthonyECrowdBotics** [CartoDB/cartodb-postgresql#353]
test test/CDB_GhostTables     ... FAILED

  BEGIN
***************
*** 13,19 ****
  0
  CREATE TABLE
  1
! WARNING:  Error calling Invalidation Service to link Ghost Tables: Error -2 connecting fake-tis-host:3142. Name or service not known.
  NOTICE:  _CDB_LinkGhostTables() called with username=fulanito, event_name=CREATE TABLE
  COMMIT

--- 13,19 ----
  0
  CREATE TABLE
  1
! WARNING:  Error trying to connect to Invalidation Service to link Ghost Tables: No module named redis
  NOTICE:  _CDB_LinkGhostTables() called with username=fulanito, event_name=CREATE TABLE
  COMMIT

Feel it has something to do with recent commit

https://github.com/CartoDB/cartodb-postgresql/pull/351/commits/a5b2b66bb6e12af3d23a003298c61c0cf79cb53a

**Comment by Algunenano** [comment]
Looks like it's missing python/pip redis.

@gonzaloriestra It seems the python redis module is now a dependency (https://github.com/CartoDB/cartodb-postgresql/commit/d1ee383d9bcf86ec906162f643f62fd7bdc50d2d#diff-354f30a63fb0907d4ad57269548329e3) for the extension. Is that correct? If so, we should update the README.

**Comment by AnthonyECrowdBotics** [comment]
Just might be. I’m happy to help update the readme. Is the connection error
due to that as well?

**Comment by gonzaloriestra** [comment]
@Algunenano Yes, I forgot to add it, thanks!

@AnthonyECrowdBotics thanks for reporting. So it's working now, right? The latest output you posted is the expected one: https://github.com/CartoDB/cartodb-postgresql/blob/74210c5b5cec34bbcba117b973d7d17ab3ad26a0/test/CDB_GhostTables_expect

**Comment by AnthonyECrowdBotics** [comment]
Seems to working
