### ISSUE TITLE
installcheck error 

### ISSUE THREAD

**Issue by Niyokee** [CartoDB/cartodb-postgresql#398]
I can't pass the tests.
Now I'm using the latest version '0.36'
```
============== running regression test queries        ==============
test test/CDB_GhostTables     ... FAILED
test test/CDB_FederatedServerDiagnostics ... FAILED
test test/CDB_FederatedServerTables ... FAILED
test test/CDB_FederatedServerListRemote ... FAILED
```

According to this issue https://github.com/CartoDB/cartodb-postgresql/issues/353#issue-447321911 
installing redis will solve this `test test/CDB_GhostTables     ... FAILED`  but it doesn't.

Can you confirm the same issue?
I will be grateful for any help you can provide.

**Comment by Algunenano** [comment]
Hi, without seeing the output of the logs it's impossible for us to diagnose this.
