### ISSUE TITLE
test test_ddl_triggers        ... FAILED

### ISSUE THREAD

**Issue by theblackdie** [CartoDB/cartodb-postgresql#60]
I followed step by step the installation procedure on a new Ubuntu 12.04 machine (updated to the latest patch)

And I have an error while testing triggers:

`sudo PGUSER=postgres make installcheck`

the error I got is : 

>
1 of 15 tests failed.
test test_ddl_triggers        ... FAILED

>
The differences that caused some tests to fail can be viewed in the
file "/home/mentis/cartodb-postgresql/regression.diffs".  A copy of the test summary that you see
above is saved in the file "/home/mentis/cartodb-postgresql/regression.out".

>
make: *** [installcheck] Error 1

>
*** /home/mentis/cartodb-postgresql/expected/test_ddl_triggers.out      2014-11-19 04:58:25.575897500 +0000
--- /home/mentis/cartodb-postgresql/results/test_ddl_triggers.out       2014-11-19 05:02:28.463897500 +0000
***************
*** 91,97 ****
  FROM CDB_TableMetadata WHERE tabname = 'c.t4'::regclass;
   tabname | age
  ---------+-----
!  c.t4    |   0
  (1 row)
>
  ----------------------------
--- 91,97 ----
  FROM CDB_TableMetadata WHERE tabname = 'c.t4'::regclass;
   tabname | age
  ---------+-----
!  c.t4    |   1
  (1 row)
>
  ----------------------------
***************
*** 122,128 ****
  from c.t3;
   cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator | i | webmerc
  ------------+-----+------+----------+----------------------+---+---------
!           1 | t   | t    |          |                      | 1 |
  (1 row)
>
  select
--- 122,128 ----
  from c.t3;
   cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator | i | webmerc
  ------------+-----+------+----------+----------------------+---+---------
!           1 | t   | f    |          |                      | 1 |
  (1 row)
>
  select
***************
*** 159,165 ****
  from c.t3;
   cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator | i | webmerc | webmerc2
  ------------+-----+------+----------+----------------------+---+---------+----------
!           1 | t   | t    |          |                      | 1 |         |
  (1 row)
>
  select
--- 159,165 ----
  from c.t3;
   cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator | i | webmerc | webmerc2
  ------------+-----+------+----------+----------------------+---+---------+----------
!           1 | t   | f    |          |                      | 1 |         |
  (1 row)
>
  select
***************
*** 199,205 ****
  from c.t3;
   cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator | i | webmerc | webmerc2
  ------------+-----+------+----------+----------------------+---+---------+----------
!           1 | t   | t    |          |                      | 1 |         |
  (1 row)
  select
--- 199,205 ----
  from c.t3;
   cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator | i | webmerc | webmerc2
  ------------+-----+------+----------+----------------------+---+---------+----------
!           1 | t   | f    |          |                      | 1 |         |
  (1 row)
>
  select
***************
*** 230,236 ****
  from c.t3;
   cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator | i | webmerc | webmerc2 | id2
  ------------+-----+------+----------+----------------------+---+---------+----------+-----
!           1 | t   | t    |          |                      | 1 |         |          |
  (1 row)
>
  select
--- 230,236 ----
  from c.t3;
   cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator | i | webmerc | webmerc2 | id2
  ------------+-----+------+----------+----------------------+---+---------+----------+-----
!           1 | t   | f    |          |                      | 1 |         |          |
  (1 row)
>
  select
>
======================================================================
`

<h1>This is the output of the file test_ddl_triggers.out</h1>
>
\set VERBOSITY terse
-- Set user quota to infinite
SELECT CDB_SetUserQuotaInBytes(0);
 cdb_setuserquotainbytes
-------------------------
                       0
(1 row)
>
-- Enable ddl triggers
SELECT cartodb.cdb_enable_ddl_hooks();
NOTICE:  event trigger "cdb_on_relation_create" does not exist, skipping
NOTICE:  event trigger "cdb_on_relation_drop" does not exist, skipping
NOTICE:  event trigger "cdb_on_alter_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_drop_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_add_column" does not exist, skipping
 cdb_enable_ddl_hooks
----------------------
>
(1 row)
>
create schema c;
CREATE USER cartodb_postgresql_unpriv_user;
GRANT ALL ON SCHEMA c to cartodb_postgresql_unpriv_user;
SET SESSION AUTHORIZATION 'cartodb_postgresql_unpriv_user';
--SELECT session_user, current_user;
----------------------
-- CREATE TABLE
----------------------
select 1 as i INTO c.t3;
NOTICE:  trigger "track_updates" for table "c.t3" does not exist, skipping
NOTICE:  trigger "update_the_geom_webmercator_trigger" for table "c.t3" does not exist, skipping
NOTICE:  trigger "update_updated_at_trigger" for table "c.t3" does not exist, skipping
NOTICE:  trigger "test_quota" for table "c.t3" does not exist, skipping
NOTICE:  trigger "test_quota_per_row" for table "c.t3" does not exist, skipping
NOTICE:  event trigger "cdb_on_relation_create" does not exist, skipping
NOTICE:  event trigger "cdb_on_relation_drop" does not exist, skipping
NOTICE:  event trigger "cdb_on_alter_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_drop_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_add_column" does not exist, skipping
NOTICE:  cdb_invalidate_varnish(c.t3) called
select
 cartodb_id, created_at=updated_at as "c=u",
 NOW() - updated_at < '1 secs' as "u<1s",
 the_geom, the_geom_webmercator,
 i
from c.t3;
 cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator | i
------------+-----+------+----------+----------------------+---
          1 | t   | t    |          |                      | 1
(1 row)
>
select
 tabname::text,
 round(extract('secs' from now()  - updated_at)) as age
FROM CDB_TableMetadata WHERE tabname = 'c.t3'::regclass;
 tabname | age
---------+-----
 c.t3    |   0
(1 row)
>
-- Table with cartodb_id field, see
-- http://github.com/CartoDB/cartodb-postgresql/issues/32
select 1 as cartodb_id INTO c.t4;
NOTICE:  trigger "track_updates" for table "c.t4" does not exist, skipping
NOTICE:  trigger "update_the_geom_webmercator_trigger" for table "c.t4" does not exist, skipping
NOTICE:  trigger "update_updated_at_trigger" for table "c.t4" does not exist, skipping
NOTICE:  trigger "test_quota" for table "c.t4" does not exist, skipping
NOTICE:  trigger "test_quota_per_row" for table "c.t4" does not exist, skipping
NOTICE:  Column cartodb_id already exists
NOTICE:  Existing cartodb_id field does not have an associated sequence, renaming
NOTICE:  Trying to recover data from _cartodb_id0 column
NOTICE:  event trigger "cdb_on_relation_create" does not exist, skipping
NOTICE:  event trigger "cdb_on_relation_drop" does not exist, skipping
NOTICE:  event trigger "cdb_on_alter_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_drop_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_add_column" does not exist, skipping
NOTICE:  cdb_invalidate_varnish(c.t4) called
select
 cartodb_id, created_at=updated_at as "c=u",
 NOW() - updated_at < '1 secs' as "u<1s",
 the_geom, the_geom_webmercator
from c.t4;
 cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator
------------+-----+------+----------+----------------------
          1 | t   | t    |          |
(1 row)
>
select
 tabname::text,
 round(extract('secs' from now() - updated_at)) as age
FROM CDB_TableMetadata WHERE tabname = 'c.t4'::regclass;
 tabname | age
---------+-----
 c.t4    |   1
(1 row)
>
----------------------------
-- ALTER TABLE RENAME COLUMN
----------------------------
select pg_sleep(.1);
 pg_sleep
----------
>
(1 row)
>
alter table c.t3 rename column the_geom_webmercator to webmerc;
NOTICE:  Column cartodb_id already exists
NOTICE:  Column created_at already exists
NOTICE:  Column updated_at already exists
NOTICE:  Column the_geom already exists
NOTICE:  event trigger "cdb_on_relation_create" does not exist, skipping
NOTICE:  event trigger "cdb_on_relation_drop" does not exist, skipping
NOTICE:  event trigger "cdb_on_alter_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_drop_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_add_column" does not exist, skipping
NOTICE:  cdb_invalidate_varnish(c.t3) called
select
 cartodb_id, created_at=updated_at as "c=u",
 NOW() - updated_at < '1 secs' as "u<1s",
 the_geom, the_geom_webmercator,
 i, webmerc
from c.t3;
 cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator | i | webmerc
------------+-----+------+----------+----------------------+---+---------
          1 | t   | f    |          |                      | 1 |
(1 row)
>
select
 tabname::text,
 round(extract('secs' from now()  - updated_at)*10) as agecs
FROM CDB_TableMetadata WHERE tabname = 'c.t3'::regclass;
 tabname | agecs
---------+-------
 c.t3    |     0
(1 row)
>
select pg_sleep(.1);
 pg_sleep
----------
>
(1 row)
>
alter table c.t3 rename column the_geom_webmercator to webmerc2;
NOTICE:  Column cartodb_id already exists
NOTICE:  Column created_at already exists
NOTICE:  Column updated_at already exists
NOTICE:  Column the_geom already exists
NOTICE:  event trigger "cdb_on_relation_create" does not exist, skipping
NOTICE:  event trigger "cdb_on_relation_drop" does not exist, skipping
NOTICE:  event trigger "cdb_on_alter_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_drop_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_add_column" does not exist, skipping
NOTICE:  cdb_invalidate_varnish(c.t3) called
select
 cartodb_id, created_at=updated_at as "c=u",
 NOW() - updated_at < '1 secs' as "u<1s",
 the_geom, the_geom_webmercator,
 i, webmerc, webmerc2
from c.t3;
 cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator | i | webmerc | webmerc2
------------+-----+------+----------+----------------------+---+---------+----------
          1 | t   | f    |          |                      | 1 |         |
(1 row)
>
select
 tabname::text,
 round(extract('secs' from now()  - updated_at)*10) as agecs
FROM CDB_TableMetadata WHERE tabname = 'c.t3'::regclass;
 tabname | agecs
---------+-------
 c.t3    |     0
(1 row)
>
----------------------------
-- ALTER TABLE DROP COLUMN
----------------------------
select pg_sleep(.1);
 pg_sleep
----------
>
(1 row)
>
alter table c.t3 drop column the_geom_webmercator;
NOTICE:  Column cartodb_id already exists
NOTICE:  Column created_at already exists
NOTICE:  Column updated_at already exists
NOTICE:  Column the_geom already exists
NOTICE:  event trigger "cdb_on_relation_create" does not exist, skipping
NOTICE:  event trigger "cdb_on_relation_drop" does not exist, skipping
NOTICE:  event trigger "cdb_on_alter_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_drop_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_add_column" does not exist, skipping
NOTICE:  cdb_invalidate_varnish(c.t3) called
select
 cartodb_id, created_at=updated_at as "c=u",
 NOW() - updated_at < '1 secs' as "u<1s",
 the_geom, the_geom_webmercator,
 i, webmerc, webmerc2
from c.t3;
 cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator | i | webmerc | webmerc2
------------+-----+------+----------+----------------------+---+---------+----------
          1 | t   | f    |          |                      | 1 |         |
(1 row)
>
select
 tabname::text,
 round(extract('secs' from now()  - updated_at)*10) as agecs
FROM CDB_TableMetadata WHERE tabname = 'c.t3'::regclass;
 tabname | agecs
---------+-------
 c.t3    |     0
(1 row)
>
----------------------------
-- ALTER TABLE ADD COLUMN
----------------------------
select pg_sleep(.1);
 pg_sleep
----------
>
(1 row)
>
alter table c.t3 add column id2 int;
NOTICE:  cdb_invalidate_varnish(c.t3) called
select
 cartodb_id, created_at=updated_at as "c=u",
 NOW() - updated_at < '1 secs' as "u<1s",
 the_geom, the_geom_webmercator,
 i, webmerc, webmerc2, id2
from c.t3;
 cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator | i | webmerc | webmerc2 | id2
------------+-----+------+----------+----------------------+---+---------+----------+-----
          1 | t   | f    |          |                      | 1 |         |          |
(1 row)
>
select
 tabname::text,
 round(extract('secs' from now()  - updated_at)*10) as agecs
FROM CDB_TableMetadata WHERE tabname = 'c.t3'::regclass;
 tabname | agecs
---------+-------
 c.t3    |     0
(1 row)
>
----------------------------
-- DROP TABLE
----------------------------
RESET SESSION AUTHORIZATION;
drop schema c cascade;
NOTICE:  drop cascades to 2 other objects
select count(*) from CDB_TableMetadata;
 count
-------
     0
(1 row)
>
DROP USER cartodb_postgresql_unpriv_user;
DROP FUNCTION _CDB_UserQuotaInBytes();

<h1>What I tried</h1>
I added schema_triggers.so to the shared_preload_libraries setting in postgresql.conf :
`$ sudo vim /etc/postgresql/9.3/main/postgresql.conf`
...
`shared_preload_libraries = 'schema_triggers.so'`

and I restarted postgresql service

`$ sudo service postgresql restart # restart postgres`

After this change the 2nd installcheck of cartodb-postresql had the same error

I reformatted the virtual machine (which is hosted in Microsoft azure for instance) and I have the same problem

**Comment by Avrelin** [comment]
Have the same issue on Ubuntu 14.04, added shared_preload_libraries = 'schema_triggers.so' and restarted postgresql service -> still no luck

Any help would be appreciated.

**Comment by mattcen** [comment]
I've the same issue. I did a clean install of Ubuntu 12.04 and followed the current cartodb installation instructions to the letter. I don't know Postgres well enough to know where to look for a solution.

**Comment by juanignaciosl** [comment]
I've just done a clean install of CartoDB under Ubuntu 12.04 by following instructions and it worked like a charm, although I had to do [the schema triggers fix that is described at cartodb-postgresql instructions](https://github.com/CartoDB/cartodb#install-cartodb-postgresql). Please check the following:
- Ubuntu version, currently only 12.04 is supported.
- [You've edited `pg_hba.conf` connections to `trust` and restarted PostgreSQL](https://github.com/CartoDB/cartodb#install-postgresql).
- [You've edited postgresql.conf with `shared_preload_libraries = 'schema_triggers.so'` and restarted PostgreSQL](https://github.com/CartoDB/cartodb#install-cartodb-postgresql).

**Comment by danseely** [comment]
I see this issue is closed, but I'm still seeing the failure of this test. Clean Ubuntu 12.04 install, following installation instructions exactly -- including editing `pg_hba.conf` and `postgresql.conf` as noted above. Below is my `test_ddl_triggers.out`.

````
\set VERBOSITY terse
-- Set user quota to infinite
SELECT CDB_SetUserQuotaInBytes(0);
 cdb_setuserquotainbytes 
-------------------------
                       0
(1 row)

-- Enable ddl triggers
SELECT cartodb.cdb_enable_ddl_hooks();
NOTICE:  event trigger "cdb_on_relation_create" does not exist, skipping
NOTICE:  event trigger "cdb_on_relation_drop" does not exist, skipping
NOTICE:  event trigger "cdb_on_alter_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_drop_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_add_column" does not exist, skipping
 cdb_enable_ddl_hooks 
----------------------
 
(1 row)

create schema c;
SELECT CDB_SetUserQuotaInBytes('c', 0);
 cdb_setuserquotainbytes 
-------------------------
                       0
(1 row)

CREATE USER cartodb_postgresql_unpriv_user;
GRANT ALL ON SCHEMA c to cartodb_postgresql_unpriv_user;
SET SESSION AUTHORIZATION 'cartodb_postgresql_unpriv_user';
--SELECT session_user, current_user;
----------------------
-- CREATE TABLE
----------------------
SET SESSION AUTHORIZATION 'cartodb_postgresql_unpriv_user';
select 1 as i INTO c.t3;
NOTICE:  trigger "track_updates" for table "c.t3" does not exist, skipping
NOTICE:  trigger "update_the_geom_webmercator_trigger" for table "c.t3" does not exist, skipping
NOTICE:  trigger "update_updated_at_trigger" for table "c.t3" does not exist, skipping
NOTICE:  trigger "test_quota" for table "c.t3" does not exist, skipping
NOTICE:  trigger "test_quota_per_row" for table "c.t3" does not exist, skipping
NOTICE:  event trigger "cdb_on_relation_create" does not exist, skipping
NOTICE:  event trigger "cdb_on_relation_drop" does not exist, skipping
NOTICE:  event trigger "cdb_on_alter_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_drop_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_add_column" does not exist, skipping
NOTICE:  cdb_invalidate_varnish(c.t3) called
select
 cartodb_id, created_at=updated_at as "c=u",
 NOW() - updated_at < '1 secs' as "u<1s",
 the_geom, the_geom_webmercator,
 i
from c.t3;
 cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator | i 
------------+-----+------+----------+----------------------+---
          1 | t   | t    |          |                      | 1
(1 row)

RESET SESSION AUTHORIZATION;
select
 tabname::text,
 round(extract('secs' from now()  - updated_at)) as age
FROM CDB_TableMetadata WHERE tabname = 'c.t3'::regclass;
 tabname | age 
---------+-----
 c.t3    |   0
(1 row)

SET SESSION AUTHORIZATION 'cartodb_postgresql_unpriv_user';
-- Table with cartodb_id field, see
-- http://github.com/CartoDB/cartodb-postgresql/issues/32
select 1 as cartodb_id INTO c.t4;
NOTICE:  trigger "track_updates" for table "c.t4" does not exist, skipping
NOTICE:  trigger "update_the_geom_webmercator_trigger" for table "c.t4" does not exist, skipping
NOTICE:  trigger "update_updated_at_trigger" for table "c.t4" does not exist, skipping
NOTICE:  trigger "test_quota" for table "c.t4" does not exist, skipping
NOTICE:  trigger "test_quota_per_row" for table "c.t4" does not exist, skipping
NOTICE:  Column cartodb_id already exists
NOTICE:  Existing cartodb_id field does not have an associated sequence, renaming
NOTICE:  Trying to recover data from _cartodb_id0 column
NOTICE:  event trigger "cdb_on_relation_create" does not exist, skipping
NOTICE:  event trigger "cdb_on_relation_drop" does not exist, skipping
NOTICE:  event trigger "cdb_on_alter_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_drop_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_add_column" does not exist, skipping
NOTICE:  cdb_invalidate_varnish(c.t4) called
select
 cartodb_id, created_at=updated_at as "c=u",
 NOW() - updated_at < '1 secs' as "u<1s",
 the_geom, the_geom_webmercator
from c.t4;
 cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator 
------------+-----+------+----------+----------------------
          1 | t   | t    |          | 
(1 row)

RESET SESSION AUTHORIZATION;
select
 tabname::text,
 round(extract('secs' from now() - updated_at)) as age
FROM CDB_TableMetadata WHERE tabname = 'c.t4'::regclass;
 tabname | age 
---------+-----
 c.t4    |   0
(1 row)

----------------------------
-- ALTER TABLE RENAME COLUMN
----------------------------
SET SESSION AUTHORIZATION 'cartodb_postgresql_unpriv_user';
select pg_sleep(.1);
 pg_sleep 
----------
 
(1 row)

alter table c.t3 rename column the_geom_webmercator to webmerc;
NOTICE:  Column cartodb_id already exists
NOTICE:  Column created_at already exists
NOTICE:  Column updated_at already exists
NOTICE:  Column the_geom already exists
NOTICE:  event trigger "cdb_on_relation_create" does not exist, skipping
NOTICE:  event trigger "cdb_on_relation_drop" does not exist, skipping
NOTICE:  event trigger "cdb_on_alter_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_drop_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_add_column" does not exist, skipping
NOTICE:  cdb_invalidate_varnish(c.t3) called
select
 cartodb_id, created_at=updated_at as "c=u",
 NOW() - updated_at < '1 secs' as "u<1s",
 the_geom, the_geom_webmercator,
 i, webmerc
from c.t3;
 cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator | i | webmerc 
------------+-----+------+----------+----------------------+---+---------
          1 | t   | t    |          |                      | 1 | 
(1 row)

RESET SESSION AUTHORIZATION;
select
 tabname::text,
 round(extract('secs' from now()  - updated_at)*10) as agecs
FROM CDB_TableMetadata WHERE tabname = 'c.t3'::regclass;
 tabname | agecs 
---------+-------
 c.t3    |     0
(1 row)

SET SESSION AUTHORIZATION 'cartodb_postgresql_unpriv_user';
select pg_sleep(.1);
 pg_sleep 
----------
 
(1 row)

alter table c.t3 rename column the_geom_webmercator to webmerc2;
NOTICE:  Column cartodb_id already exists
NOTICE:  Column created_at already exists
NOTICE:  Column updated_at already exists
NOTICE:  Column the_geom already exists
NOTICE:  event trigger "cdb_on_relation_create" does not exist, skipping
NOTICE:  event trigger "cdb_on_relation_drop" does not exist, skipping
NOTICE:  event trigger "cdb_on_alter_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_drop_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_add_column" does not exist, skipping
NOTICE:  cdb_invalidate_varnish(c.t3) called
select
 cartodb_id, created_at=updated_at as "c=u",
 NOW() - updated_at < '1 secs' as "u<1s",
 the_geom, the_geom_webmercator,
 i, webmerc, webmerc2
from c.t3;
 cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator | i | webmerc | webmerc2 
------------+-----+------+----------+----------------------+---+---------+----------
          1 | t   | t    |          |                      | 1 |         | 
(1 row)

RESET SESSION AUTHORIZATION;
select
 tabname::text,
 round(extract('secs' from now()  - updated_at)*10) as agecs
FROM CDB_TableMetadata WHERE tabname = 'c.t3'::regclass;
 tabname | agecs 
---------+-------
 c.t3    |     0
(1 row)

----------------------------
-- ALTER TABLE DROP COLUMN
----------------------------
SET SESSION AUTHORIZATION 'cartodb_postgresql_unpriv_user';
select pg_sleep(.1);
 pg_sleep 
----------
 
(1 row)

alter table c.t3 drop column the_geom_webmercator;
NOTICE:  Column cartodb_id already exists
NOTICE:  Column created_at already exists
NOTICE:  Column updated_at already exists
NOTICE:  Column the_geom already exists
NOTICE:  event trigger "cdb_on_relation_create" does not exist, skipping
NOTICE:  event trigger "cdb_on_relation_drop" does not exist, skipping
NOTICE:  event trigger "cdb_on_alter_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_drop_column" does not exist, skipping
NOTICE:  event trigger "cdb_on_add_column" does not exist, skipping
NOTICE:  cdb_invalidate_varnish(c.t3) called
select
 cartodb_id, created_at=updated_at as "c=u",
 NOW() - updated_at < '1 secs' as "u<1s",
 the_geom, the_geom_webmercator,
 i, webmerc, webmerc2
from c.t3;
 cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator | i | webmerc | webmerc2 
------------+-----+------+----------+----------------------+---+---------+----------
          1 | t   | t    |          |                      | 1 |         | 
(1 row)

RESET SESSION AUTHORIZATION;
select
 tabname::text,
 round(extract('secs' from now()  - updated_at)*10) as agecs
FROM CDB_TableMetadata WHERE tabname = 'c.t3'::regclass;
 tabname | agecs 
---------+-------
 c.t3    |     0
(1 row)

----------------------------
-- ALTER TABLE ADD COLUMN
----------------------------
SET SESSION AUTHORIZATION 'cartodb_postgresql_unpriv_user';
select pg_sleep(.1);
 pg_sleep 
----------
 
(1 row)

alter table c.t3 add column id2 int;
NOTICE:  cdb_invalidate_varnish(c.t3) called
select
 cartodb_id, created_at=updated_at as "c=u",
 NOW() - updated_at < '1 secs' as "u<1s",
 the_geom, the_geom_webmercator,
 i, webmerc, webmerc2, id2
from c.t3;
 cartodb_id | c=u | u<1s | the_geom | the_geom_webmercator | i | webmerc | webmerc2 | id2 
------------+-----+------+----------+----------------------+---+---------+----------+-----
          1 | t   | t    |          |                      | 1 |         |          |    
(1 row)

RESET SESSION AUTHORIZATION;
select
 tabname::text,
 round(extract('secs' from now()  - updated_at)*10) as agecs
FROM CDB_TableMetadata WHERE tabname = 'c.t3'::regclass;
 tabname | agecs 
---------+-------
 c.t3    |     1
(1 row)

----------------------------
-- DROP TABLE
----------------------------
RESET SESSION AUTHORIZATION;
drop schema c cascade;
NOTICE:  drop cascades to 3 other objects
select count(*) from CDB_TableMetadata;
 count 
-------
     0
(1 row)

DROP USER cartodb_postgresql_unpriv_user;
DROP FUNCTION _CDB_UserQuotaInBytes();

````

**Comment by danseely** [comment]
Oddly, test now passes after a system reboot. ¯\_(ツ)_/¯

**Comment by juanignaciosl** [comment]
Restarting PostgreSQL (twice) worked for me  ¯_(ツ)_/¯

**Comment by danseely** [comment]
That's interesting, I wonder if PostgreSQL just needed another restart. Hmm.

**Comment by pramsey** [comment]
Well, the ddl triggers are loaded in a preload so certainly a single restart would be required at a minimum to get fresh ones up and running

**Comment by dhthong92** [comment]
Well, I've try 3 times in different computers but also failed. But the problem is I've built it success three days ago, in another computer. My OS is Ubuntu LTS 14.04. I don't know what happens  and how to solved, seem like still exist any bug in there

**Comment by juanignaciosl** [comment]
Currently we only support Ubuntu 12.04. It doesn't mean you can't install it elsewhere, of course, but it might be more difficult as installation guide only covers that version.
