### ISSUE TITLE
CDB_UserTables returns 0 entries for multiuser accounts

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb-postgresql#64]

**Comment by elesdoar** [comment]
Sometimes returns ```geocoding_cache_xxxxx ``` tables

**Comment by danicarrion** [comment]
I'm not really into the details of what exactly CDB_UserTables must return, but this query returns the same result as current CDB_UserTables does for a regular user, for both a regular user and a user that is part of an organization, at least in the few tests I've done:

```sql
select pg_class.relname from pg_class, pg_roles, pg_namespace where pg_roles.oid = pg_class.relowner and pg_roles.rolname = current_user and pg_namespace.oid = pg_class.relnamespace and pg_class.relkind = 'r'
```

**Comment by pramsey** [comment]
I think this query is expected to be runnable by anyone, both public and private, so accessing the system tables may not be allowed (unless that has changed...)

**Comment by javisantana** [comment]
this should return public tables only

**Comment by pramsey** [comment]
In order to fix this function, it would be great to know what it's supposed to be doing. Since it's broken, we can't figure that out be examining the code itself. Could you give us the precise information it's supposed to be returning?

**Comment by pramsey** [comment]
Variation on @danicarrion's result, removing system tables
```sql
select c.relname 
from pg_class c 
join pg_roles r on r.oid = c.relowner
join pg_namespace n on n.oid = c.relnamespace
where r.rolname = current_user 
and c.relkind = 'r' 
and c.relname not in ('cdb_tablemetadata', 'spatial_ref_sys')
and n.nspname not in ('pg_catalog', 'information_schema');
```

**Comment by danicarrion** [comment]
I've checked Paul's function with an org user and the results make sense to me.

**Comment by pramsey** [comment]
No kidding, playing with the guts blind gives me the willies.

**Comment by danicarrion** [comment]
@javisantana who can we ping about this?

**Comment by javisantana** [comment]
@danicarrion -> @pramsey

**Comment by pramsey** [comment]
Hokay, I'm going to go on the theory that if I can pass the tests in the repo, it's safe to commit...

**Comment by danicarrion** [comment]
i can cross my fingers if that helps ;-)

**Comment by pramsey** [comment]
Pull request #83 should do the trick (inshalah)

**Comment by pramsey** [comment]
Hey @rochoa how do you feel about a 0.7.4 release?

**Comment by rochoa** [comment]
We should! Shouldn't we?

I will try to get out a new version by EOW, does that work for you?

**Comment by pramsey** [comment]
It entirely does work for me.

**Comment by pramsey** [comment]
Hey @rochoa, I don't see a new version number in the repo, should that happen when a new version is released?

**Comment by rafatower** [comment]
The `name` type can give some headaches https://github.com/CartoDB/cartodb-postgresql/pull/83#discussion-diff-33560557

We should define what's part of the "public API" and what's not and be careful when changing function signatures.

I'm gonna open an issue to add a migration test to the suite.

**Comment by javisantana** [comment]
fixed https://javi.cartodb.com/api/v1/sql?q=select%20count(*)%20from%20cdb_usertables()

ref https://github.com/CartoDB/cartodb-postgresql/commit/df36e83cb552bb8cb287a12b53a562730003807f

**Comment by elesdoar** [comment]
:+1:

**Comment by cayetanobv** [comment]
Hi team, just FYI (and if it is useful for other users maybe you can adjust the behavior of the function with a new parameter...)
We have a use case in a "multiuser enterprise account" where we need to know exactly what tables owns each user (public and privates). Each user corresponds to a different geographical area. We modified function CDB_Tables() for that purpose (with "theuser" as argument):
```sql
CREATE OR REPLACE FUNCTION GetUserTables(theuser text)
  RETURNS SETOF name
  AS $$
  SELECT c.relname
  FROM pg_class c 
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE c.relkind = 'r' 
  AND c.relname NOT IN ('cdb_tablemetadata', 'spatial_ref_sys')
  AND n.nspname NOT IN ('pg_catalog', 'information_schema', 'topology', 'cartodb')
  AND n.nspname = theuser
  $$ LANGUAGE 'sql';
```

Thanks!

**Comment by alasarr** [comment]
We've faced out with this issue several times. I think we should explain it at the doc, I'm sending a PR.
