### ISSUE TITLE
Long table names causing trouble

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb-postgresql#86]
See https://github.com/CartoDB/cartodb/issues/3808

The problem is the 63 char limit for identifiers.
- `CDB_QueryTables` returns `name[]`, containing `"schema.table"`'s that can exceed 63 chars in total
- When trying to join that with `CDB_TablesMetadata`, `name`'s potentially do not fit in a `regclass`

We should probably modify `CDB_QueryTables` to return `(schema, table)` pairs

**Comment by rafatower** [comment]
Some quick tests against 9.3:
```sql
-- String literal to regclass OK
SELECT (('public.bug3808_renamed_cpre_charter_to_save_our_countryside_comments_e')::regclass);

-- String literal to NAME to regclass ERROR
SELECT (('public.bug3808_renamed_cpre_charter_to_save_our_countryside_comments_e')::name::regclass);

-- String to name to text to regclass ERROR
SELECT (('public.bug3808_renamed_cpre_charter_to_save_our_countryside_comments_e')::name::text::regclass);
```
It will be hard to find a workaround for this without modifying `CDB_QueryTables`

**Comment by rafatower** [comment]
Makes sense since `name` is limited to 64 bytes: http://www.postgresql.org/docs/9.3/static/datatype-character.html

The quickest thing to do is create another version of `CDB_QueryTables` with different return type.

**Comment by rochoa** [comment]
With the help of @rafatower we just validated that using regclass[] as return type would fix some of the problems we have in https://github.com/CartoDB/Windshaft-cartodb/blob/2.5.0/lib/cartodb/api/query_tables_api.js#L36-L43 Find bellow a patch.

However changing the return type might break some uses of the function.

```patch
diff --git a/scripts-available/CDB_QueryTables.sql b/scripts-available/CDB_QueryTables.sql
index cd8b51b..c304553 100644
--- a/scripts-available/CDB_QueryTables.sql
+++ b/scripts-available/CDB_QueryTables.sql
@@ -3,11 +3,11 @@
 -- Requires PostgreSQL 9.x+
 --
 CREATE OR REPLACE FUNCTION CDB_QueryTables(query text)
-RETURNS name[]
+RETURNS REGCLASS[]
 AS $$
 DECLARE
   exp XML;
-  tables NAME[];
+  tables REGCLASS[];
   rec RECORD;
   rec2 RECORD;
 BEGIN
@@ -41,11 +41,11 @@ BEGIN
           xpath('//x:Relation-Name/text()', exp, ARRAY[ARRAY['x', 'http://www.postgresql.org/2009/explain']]) as x,
           xpath('//x:Relation-Name/../x:Schema/text()', exp, ARRAY[ARRAY['x', 'http://www.postgresql.org/2009/explain']]) as s
       )
-      SELECT unnest(x)::name as p, unnest(s)::name as sc from inp
+      SELECT unnest(x) as p, unnest(s) as sc from inp
     LOOP
       -- RAISE DEBUG 'tab: %', rec2.p;
       -- RAISE DEBUG 'sc: %', rec2.sc;
-      tables := array_append(tables, (rec2.sc || '.' || rec2.p)::name);
+      tables := array_append(tables, (rec2.sc || '.' || rec2.p)::regclass);
     END LOOP;

     -- RAISE DEBUG 'Tables: %', tables;
```

**Comment by rafatower** [comment]
I thought of writing a new func called `CDB_QueryTablesRegclass` and then rewrite the original `CDB_QueryTables` ~~but then it loses the information about the schema.~~.

A better option is to check if it always does automatic casting from regclass to name when required (I guess we can write a test for that) and go ahead and change the function's signature.

**Comment by rafatower** [comment]
@javisantana @rochoa @pramsey looking forward to hear your opinion on my comment right above.

My vote for option 2.

**Comment by pramsey** [comment]
2 or 3. If you can make the global change, why not? Less complexity in long run
